### ISSUE TITLE
URL-Command for open Add-new-entry Mask

### ISSUE THREAD

**Issue by navid-kalaei** [kartevonmorgen/kartevonmorgen.ts#101]
https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/94

redirect https://kartevonmorgen.org/#/?addentry=company
to https://new.kartevonmorgen.org/m/main/e/create?c=50.8260%2C10.9200&z=7.00

**Comment by wellemut** [comment]
The URL command to create new entry is already there: https://new.kartevonmorgen.org/m/main/e/create?c=50.8260%2C10.9200&z=7.00

- [ ] Redirection is still needed.
- [ ] The type of entry should be choosable in the URL

**Comment by navid-kalaei** [comment]
fixed for the event.

- https://dev.kartevonmorgen.org/#/?addentry=initiative&search=%23ideenerfahren17
- https://dev.kartevonmorgen.org/#/?addentry=company&search=%23ideenerfahren17
- https://dev.kartevonmorgen.org/#/?addentry=event&search=%23ideenerfahren17

**Comment by wellemut** [comment]
not yet testable.
- not working on dev
- not deployed on productive

i will test it later.

**Comment by wellemut** [comment]
everything is working! https://www.kartevonmorgen.org/m/main/e/create?tag=ideenerfahren17&addentry=event&c=50.8260%2C10.9200&z=15.00
