### ISSUE TITLE
Choose better date-picker without "ok" button

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#104]
## Problem
User report, that they can not add events. 
I guess that in most cases, they just dont klick the "ok" button, after they have selected their time

![grafik](https://user-images.githubusercontent.com/15019030/159149213-4b6ac902-c932-4646-bafb-2e7f00978495.png)

## Solution
- [x] The time must be selected just by clicking the time, without any confirmation on "ok" button
-  [x] The Ende-Time should be automatically set to 'start-time +1h' so that people cant forget to choose it.

**Comment by navid-kalaei** [comment]
done. the "ok" button is still there but the duration will be saved even if the button is not clicked.

**Comment by wellemut** [comment]
Its working very nicely now
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/57217adc-33ce-4b45-b060-495082dd4e89)

time and date is saved even if you forget to click ok. 

Perfekt!
