### ISSUE TITLE
Make Logos on Landingpage in original ration

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#107]
### Problem
These logos are not in ratio
![grafik](https://user-images.githubusercontent.com/15019030/162568556-cafcc1a7-db54-4e4e-be9c-7e6bd34847f5.png)

### Solution
- [x] Makes logos allways in the correct ratio
- [x] remove the Mannheim-Logo
- [x] remove all three "Partner" Logos

**Comment by navid-kalaei** [comment]
done on commit a32904798eda7cd2b3a1afd1b6840dc7ec62899c

1. corrected the ratio of ideen and slowtech
2. removed partner logos

**Comment by wellemut** [comment]
@wellemut upload logos in correct size

**Comment by wellemut** [comment]
ratio is correct. 
But immage size is too different, just because the ideen³ logo has too much boarders.
Therefore uploaded better logos here: https://github.com/kartevonmorgen/kartevonmorgen/issues/822#issuecomment-1434308002
