### ISSUE TITLE
add/ edit entry Formular closes/reloads when hiding sidebar 

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#109]
## problem
- When I close and reopen the sidebar, where I have entered a search https://www.kartevonmorgen.org/m/main?c=49.0235%2C7.1741&z=7.00&search=b%C3%BCcherschrank+b%C3%BCcherregal+b%C3%BCchertausch+tauschregal, the filters get removed! Filter removing happens while reopening the sidebar.
- When I have opened an entry with a filtered view in the background (https://www.kartevonmorgen.org/m/main/e/7f3a3d8a9239499d81d085395923743d?c=49.0271%2C7.1741&z=7.00&search=werkstatt+reparatur+upcycling+kreislaufwirtschaft+circulareconomy+sharing) all filteres get lost, if I go back to the result list
- When I close the sidebar (to see the map and to position the pin) everything that I entered to the company gets lost and the formula still is open, but completely reset as an empty initiative.

## solutions
- [x] opening and closing of sidebar should not change anything in the filters https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/161
- [x] opening and closing entry-detailed-view should not remove the filters
- [x] never reset the Formular when hiding the sidebar
- [x] and also not, when changing entry type #96

**Comment by wellemut** [comment]
@navid-kalaei I just realized a bug. The filtering of the map is closed, whenever there is an action with the sarch result list (closing and reopening the sidebar or opening and leaving and entry-detail).
You can check it out on this link https://www.kartevonmorgen.org/m/main?c=48.8900%2C9.4592&z=7.00&search=Lebensmittel+bio+food+gem%C3%BCse+obst
![grafik](https://user-images.githubusercontent.com/15019030/213877568-fe4fcc75-6461-440f-befe-24f92cfc5d75.png)

- when you open a search result and close it again, the filters are gone
- when you close the sidebar and open it again, the filters are gone
- when you open the add-entry-formular and close it again, all filters are gone...

Probably the most annoying bug currently.

**Comment by navid-kalaei** [comment]
@wellemut resolved on ticket #161
