### ISSUE TITLE
Create the sharing modal

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#11]
# Problem
Only few people find the sharing button as it is now.
- we need to make it easier findable

# Solution
- Show and Icon and Text
 - Do it like youtube and use the same sharing-arrow and write "Share" next to it
![grafik](https://user-images.githubusercontent.com/15019030/126625549-31616524-15d4-4203-bb8f-52e056a7a16d.png)

Share button 
![grafik](https://user-images.githubusercontent.com/15019030/128029895-a6318c5b-c097-420b-a326-be3a88a9907b.png)

Includ behind this "Share-Button" several Tabs:
1. The link of the map (and if you want a direct button to share it in Twitter, Facebook, WhatsApp, Telegram...)
   - ![grafik](https://user-images.githubusercontent.com/15019030/128028513-757c64af-ba98-4538-a7d0-18e22aa4d170.png)
     - With options if you want to always show events in the future (start-time = now) default 
     - or if the start-time is fixed to the moment of sharing the link 
2. The HTML-Code for the iframe

3. The Subscription-field to enter your **mail for subscriptions** https://github.com/kartevonmorgen/openfairdb/issues/258
  - with the options to choose the frequency:  
    - Weekly digest
    - Dayly Digest (default)
    - Single mail for every change (mails are only send one hour after the last change of an entry is done) 
 The Subscription window send it to the backend, together with the bbox and filters (tags) of the current mapview
    - receive only new entries / receive every change

----
That is the old issue of this fuction: https://github.com/kartevonmorgen/kartevonmorgen/issues/512

**Comment by wellemut** [comment]
![grafik](https://user-images.githubusercontent.com/15019030/128014104-efc6d5de-5d61-44c9-988e-37df9b87fca7.png)

**Comment by Keizak** [comment]
I will take this

**Comment by navid-kalaei** [comment]
@Keizak is waiting for the subscription API. is the endpoint ready to use? and where he can find the documentation? @flosse @wellemut

**Comment by Keizak** [comment]
@flosse @wellemut I have a problem with api 
![image](https://user-images.githubusercontent.com/64217194/128594837-e1daa413-43db-4f12-aaad-1f0fe1d916e6.png)

**Comment by Keizak** [comment]
I have a problem with a subscription request, but the rest of the tasks are complete. It would be great for you to check and be able to complete other tasks. I open pull-request https://github.com/kartevonmorgen/kartevonmorgen-v1/pull/24

**Comment by wellemut** [comment]
I really love the new sharing button! is really beautiful and clean.
And i also like the white colour. It is really a great thing @Keizak !

**Comment by wellemut** [comment]
@navid-kalaei you are welcome to make it live on https://ssr.kartevonmorgen.org too!

**Comment by wellemut** [comment]
## Mail-subscription formular can be much simpler!
Is this the right issue to comment on this function?  Or do we have an own for this?

The bbox and the tags are already defined by the map-view, the user has behind the popup.
Exactly like with the iframe-code, its also visible in the URL and the user should not be asked here to filter again! 
(Just immagin that a user uses this subscription fuctin within an iframe of a spcific topic. He would not even know, what the map is filtered for. so the user should only be asked the sending details)
![grafik](https://user-images.githubusercontent.com/15019030/128739216-449c651c-ec41-4171-a874-ab8ef3dabebf.png)

**Comment by wellemut** [comment]
> I have a problem with a subscription request, but the rest of the tasks are complete. It would be great for you to check and be able to complete other tasks. I open pull-request #24

Now the subscription server is running!
https://github.com/kartevonmorgen/openfairdb/issues/258#issuecomment-894298571
