### ISSUE TITLE
Editing event: Timezone Bug

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#111]
## Problem
It seems, that the frontend displays a different timezone while editing the event than when it is shown.

Example: https://www.kartevonmorgen.org/m/main/ev/f3c31d7c1ad4422d9c3193ae00864cda?c=49.7164%2C11.0674&z=12.00&search=Clean+Up&type=event

- While editing: 
![grafik](https://user-images.githubusercontent.com/15019030/164750932-1f53f5bb-a59d-4720-8ade-4a2d18fd861d.png)

- While displaying:
![grafik](https://user-images.githubusercontent.com/15019030/164751039-55362790-8d9b-40ce-852e-39bae845263b.png)

## Solution 
- [ ] Save event in UTC https://app.swaggerhub.com/apis/Kartevonmorgen/openfairdb/0.10.5#/Events/post_events
- [ ] Kartevonmorgen.org should run in CET (Berlin)
- [ ] Display the event in the same timezone than while editing it.

**Comment by navid-kalaei** [comment]
fixed. the problem was I was converting the time to UTC before displaying on event's detail

**Comment by wellemut** [comment]
https://dev.kartevonmorgen.org/m/main is not running, so i can not test it.

**Comment by wellemut** [comment]
This seems to be working on dev. please push it to the live version!
(Just had the same problem here: 18ab0220d06d47aeac91f00644710526
This is wrong: https://www.kartevonmorgen.org/m/main/ev/18ab0220d06d47aeac91f00644710526?c=50.5550%2C10.4150&z=5.00&search=webinarvonmorgen

This is right https://v0.kartevonmorgen.org/#/?entry=18ab0220d06d47aeac91f00644710526&zoom=15.00&dropdowns=kvm

**Comment by wellemut** [comment]
perfect, its solved!
