### ISSUE TITLE
Make orgTag run correctly

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#116]
orgTags give organisations the tool to have controlled maps where nobody else can change things directly. https://blog.vonmorgen.org/en/moderated-maps/
orgTag-Owner can login to the clearance center https://openfairdb.org/clearance to approve all changes, made by others. Only than, the change will appear in their iframe. 

All this fuction is controlled by a little attribution to the URL &orgTag=m4h
The API describes more: https://app.swaggerhub.com/apis/Kartevonmorgen/openfairdb/0.10.5#/Entries%2FPlaces/get_entries__ids_ 

------

### Test 6 orgTag
1. Old URL: https://kartevonmorgen.org/#/?entry=1ac56c70146a46af8431be912d2b586b&center=51.685,12.244&zoom=15.00&orgTag=m4h&dropdowns=kvm
![grafik](https://user-images.githubusercontent.com/15019030/155291603-ddd2a624-ec06-4142-be7b-d667d4aa22df.png)
 (compare this controlled-headline with least unapproved Version without orgTag: https://kartevonmorgen.org/#/?entry=1ac56c70146a46af8431be912d2b586b&center=51.685,12.244&zoom=15.00&dropdowns=kvm
 ![grafik](https://user-images.githubusercontent.com/15019030/155291661-cafdce9e-1337-42a4-a11a-05ff92c31e33.png)
2. with dev: https://dev.kartevonmorgen.org/#/?entry=1ac56c70146a46af8431be912d2b586b&center=51.685,12.244&zoom=15.00&orgTag=m4h&dropdowns=kvm
3. redirects to https://dev.kartevonmorgen.org/m/kvm/e/1ac56c70146a46af8431be912d2b586b?c=51.6850%2C12.2440&z=15.00&orgTag=m4h which is theoretically correct, just the orgTag lost its funcitonality
:x: orgTags not working

- [x] orgTag functionallity needs to be implemented.

**Comment by navid-kalaei** [comment]
fixed. I send org_tag in [the search request](https://github.com/kartevonmorgen/kartevonmorgen.ts/blob/d184a356d830c93dce0f6103447442f53fc37ced/components/SearchEventsListener.tsx#L100) and [the entry fetcher](https://github.com/kartevonmorgen/kartevonmorgen.ts/blob/d184a356d830c93dce0f6103447442f53fc37ced/components/EntryDetail.tsx#L53).

**Comment by wellemut** [comment]
@navid-kalaei https://dev.kartevonmorgen.org/ seems not to be running. Where is it deployed?

**Comment by navid-kalaei** [comment]
it's hosted on my server. the server provider sent me an email that they're shutting down the servers from 18:30 to 21:30 Berlin time on Jul 3rd. nginx and GitHub workers are recovered successfully but kartevonmorgen did not start. I'm debugging the reasons.

it is worthy to mention my personal server is not stable and it's only usage is testing the developments. for the usecases that we need stability and availability we should migrate to a more reliable server.

**Comment by wellemut** [comment]
- [x] OrgTag is correctly showing the (different) approved version if I am using it in the URL https://www.kartevonmorgen.org/m/kvm/e/1ac56c70146a46af8431be912d2b586b?c=51.6850%2C12.2440&z=15.00&orgTag=m4h
- [ ] ❌ But it falsly does also filter. This is not intended as we have many maps which should show more entries, than those containing the orgtag... https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/146
