### ISSUE TITLE
Remove the login-Button from the header menu and make up for landingpage

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#118]
## Bugs
Some links in the Header dont work 
![grafik](https://user-images.githubusercontent.com/15019030/165387622-53f80466-397f-4776-abfd-aefeb15feab8.png)

- [x] Remove "Login" completly . We have to implement it first, but probably different...
- [x] Redirect "Kontakt" to https://blog.vonmorgen.org/kontakt/ en: https://blog.vonmorgen.org/en/contact/ es https://blog.vonmorgen.org/es/contact/ ...

- [x] Center the Landingpage kompletly. In some parts its aligned to the left
![grafik](https://user-images.githubusercontent.com/15019030/165388083-2ea792be-4ba3-44b2-b66b-9bc6339dff75.png)

- [x] Eather remove the facebook link in the footer, or add all other social networks as well
![grafik](https://user-images.githubusercontent.com/15019030/165388405-5c8c4b7c-20bb-446f-8304-a5ad152c87f6.png)

[t.me/vonmorgen](https://t.me/vonmorgen)
    [Twitter.com/kartevonmorgen](https://twitter.com/kartevonmorgen)
    [Wechange.de/Project/Karte-von-morgen](https://wechange.de/project/karte-von-morgen-in-allen-unistadten)
    oder [fb.com/vonmorgen](https://www.facebook.com/vonmorgen)
- [x] Use Icons
- [x] Here the one for WECHANGE https://nextcloud.wechange.de/s/xLPZHFDSr4GZRz4

- [x] Remove these logo https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/107

![grafik](https://user-images.githubusercontent.com/15019030/171365006-f8dbe616-b3d5-49c5-8ca2-be042b4f18ec.png)

- [x] Make Ideen³ in correct ration

**Comment by navid-kalaei** [comment]
done on commit a32904798eda7cd2b3a1afd1b6840dc7ec62899c

1. remove login from navbar
2. redirect contact to von morgen blog depending on locale
3. center the images on the homepage
4. add full contacts in the footer
5. add icons to the contacts in the footer
6. remove partners from the landing (#107)
7. correct ideen and slowtech ratios (#107)

**Comment by wellemut** [comment]
![grafik](https://user-images.githubusercontent.com/15019030/210475548-5e5da63d-9508-4ab2-9837-a03d8d1acad4.png)
Perfectly running on https://dev.kartevonmorgen.org/
-> produktive!
