### ISSUE TITLE
Translate Map and Landingpage to russian

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#12]
Landingpage is kartevonmorgen.org or the new one https://ssr.kartevonmorgen.org/
- Take the english files and translate it to Russian: https://github.com/kartevonmorgen/kartevonmorgen-v1/tree/develop/locales

**Comment by wellemut** [comment]
@navid-kalaei 
could you already start to create a folder for the russian translation with all files, that need translation?

**Comment by wellemut** [comment]
Could be a tasks for non-techies: https://nextcloud.community.civilsocietycooperation.net/apps/deck/#/board/15/card/79

**Comment by wellemut** [comment]
@dmitrap Where is the russian translation? In the folder on our branche, I dont see rusian: https://github.com/kartevonmorgen/kartevonmorgen.ts/tree/derivation/co-map.ru/main/locales
Where could it be?

**Comment by navid-kalaei** [comment]
@dmitrap @wellemut i could find it on the Nikkita's repo either https://github.com/AndrusovN/kartevonmorgen-v1/tree/develop/locales

**Comment by wellemut** [comment]
@navid-kalaei Here is the russian language File: https://github.com/AndrusovN/kartevonmorgen-v1/tree/co-map/locales/ru

Its really hard to find, so we asked @AndrusovN to do a pull request to your reposit

**Comment by wellemut** [comment]
Russian is availiable. Just need to be merged https://crowdin.com/project/kartevonmorgen/ru
