### ISSUE TITLE
Main Checkboxes should start a search, not filtering

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#123]
## Problem
- At the moment, the tags behind the main checkboxes gets add to the tags field.
- this is bad, because if you have several tags, there is no search result at all because it is filtering only for entries which have all tags.
![grafik](https://user-images.githubusercontent.com/15019030/166293777-4f09dcaa-ff01-494a-80a6-9e45c1652980.png)

## Solution
- [ ] Let the tags behind the checkboxes be added to the search bear, which is a larger search that returns all entries which match at least one of the tags.

**Comment by navid-kalaei** [comment]
appending the tags to the end of the search term is a bad design since the place for tags is the input from the filters area. this matter is fixed by concatenating tags in the request which we send to the back-end. this way we have the logical `or` between tags while keeping the search input clean.

**Comment by navid-kalaei** [comment]
done on commit c7b27ac13e7db676c2f3e5e0c652c40677c67942

**Comment by wellemut** [comment]
Perfectly running on https://dev.kartevonmorgen.org/
![grafik](https://user-images.githubusercontent.com/15019030/210474842-338ea006-8400-4a2d-8651-dc466efd079f.png)

-> produktive!
