### ISSUE TITLE
Search and filters dont work for Events

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#124]
## Problem
This is just about Events:
On the Map:
- ❌ `&tag=fortbildungenfürengagierte` When using filters, events don't popup at all on the map: https://www.kartevonmorgen.org/m/main?c=48.0691%2C7.8683&z=11.00&end_min=1628000000&type=event&tag=fortbildungenf%C3%BCrengagierte
- ✅  `&search=fortbildungenfürengagierte` While searching it is working on the map: https://www.kartevonmorgen.org/m/main?c=48.0256%2C7.8617&z=12.00&end_min=1628000000&type=event&search=fortbildungenf%C3%BCrengagierte

In the Table:
- ❌ `text=fortbildungenf%C3%BCrengagierte` is not working anymore, but it was working in an old version: https://ssr.kartevonmorgen.org/t/kvm?start_min=1628000000&text=fortbildungenf%C3%BCrengagierte&bbox=47.7840960124138%2C7.522201538085938%2C48.291873785961066%2C8.18412780761719
- ❌ `&tag=fortbildungenf%C3%BCrengagierte` is not working at all https://www.kartevonmorgen.org/t/kvm?start_min=1628000000&tag=fortbildungenf%C3%BCrengagierte&bbox=47.7840960124138%2C7.522201538085938%2C48.291873785961066%2C8.18412780761719
  - ✅ `&tag=klimafit` But simple tags without special signs are working: https://www.kartevonmorgen.org/t/kvm?start_min=1628000000&tag=klimafit&bbox=47.7840960124138%2C7.522201538085938%2C48.291873785961066%2C8.18412780761719
- ❌ `&search=fortbildungenfürengagierte` is not limit any results: https://www.kartevonmorgen.org/t/kvm?start_min=1628000000&search=fortbildungenf%C3%BCrengagierte&bbox=47.7840960124138%2C7.522201538085938%2C48.291873785961066%2C8.18412780761719

### Solution
- [ ] make the table searchable and filterable just like the map https://github.com/kartevonmorgen/kartevonmorgen/issues/374
- [ ] also use the same URL-Codes (`tag` and `search` instead of `text`)
- [ ] Adopt the Iframe-Creator, to make correct iframes

**Comment by wellemut** [comment]
@navid-kalaei 
Thank you for fixing the ssr. domain: https://ssr.kartevonmorgen.org/t/kvm?start_min=1628000000&text=fortbildungenf%C3%BCrengagierte&bbox=47.7840960124138%2C7.522201538085938%2C48.291873785961066%2C8.18412780761719

But it would be really great, if our partner could transfer to the main URL, because ssr. has other problems too, like showing only english dates, which is already solved on final version.

So as soon as you have fixed this filtering, we can ask our partners to use the final domain...

**Comment by wellemut** [comment]
SSR is used here, as long as the main domain does not support the search: https://treffpunkt-freiburg.de/fortbildungen-f%C3%BCr-engagierte-region-freiburg

**Comment by navid-kalaei** [comment]
1. now the tags are concatenated at the end of the search term instead of sending them in the `tags`. the reasons are: firstly when multiple tags are selected, the expected behavior is to `or` the queries not `and` between them. secondly, `ofdb` does not understand special characters when they are present in the tag field.

**Comment by wellemut** [comment]
Its working great! Clients are happy!
