### ISSUE TITLE
No OSM Tile Visible on localhost

### ISSUE THREAD

**Issue by navid-kalaei** [kartevonmorgen/kartevonmorgen.ts#125]
## Problem
OSM is free, but the tiles are not. I'm cannot see the map tiles anymore on the dev mode on my localhost.

## Tried Solutions
- port-forwarding to servers (French and Germany) ❌ 
- openconnect vpn ❌
- shadowsocks to Britain ❌  
- Tor ☑️ 
- changing the tile server ✅ 

Tor worked but is not a solution because Tor Browser does not recognize localhost

![Screenshot from 2022-05-04 17-54-51](https://user-images.githubusercontent.com/7106251/166690641-8d030b1f-2f85-453d-b017-3f04ebee3b56.png)

**Comment by wellemut** [comment]
I guess you have a local blockage in Iran. 

on my side it is working perfectly

![grafik](https://user-images.githubusercontent.com/15019030/166692121-40be5c40-e88c-4741-9905-7422436d3fbc.png)

**Comment by alex0107** [comment]
I think this is maybe a rate limit?

**Comment by navid-kalaei** [comment]
I changed the OSM tile server from the official resource to the Germany edition and it solved the issue.

list of tile servers can be found [here](https://wiki.openstreetmap.org/wiki/Tile_servers)
