### ISSUE TITLE
Direct Link on entries does not center correctly

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#126]
## Problem
Using a direct link to an entry opens the sidebar info correctly, but does not center the map correctly but just on Germany

Example: https://www.kartevonmorgen.org/m/main/ev/eeef6883f5a843c995e947b11521126d

## Solution
- The entry should be centered on the map with &zoom=15.00

Example: https://v0.kartevonmorgen.org/#/?entry=eeef6883f5a843c995e947b11521126d

**Comment by navid-kalaei** [comment]
I also found an other problem. we zoom on the pin but it's very easy to confuse the correct pin with others since the pin colors are very similar. shall I open a tooltip above the centered pin to emphasis? in my eyes highlighting is not enough. what do you think @wellemut ?

**Comment by navid-kalaei** [comment]
@wellemut we have the `default_zoom` and the `close_zoom` for the map. should I change the close zoom to 15 or rename it to the reginional zoom and add the value 15 as the close zoom? to simplify I rewrite the two alternatives, please choose one.

A. 
```json
{
  "map":{
    "default_zoom":6.0,
    "close_zoom":12.0
  }
}
```

B.
```json
{
  "map":{
    "default_zoom":6.0,
    "close_zoom":15.0,
    "reginional_zoom":12.0
  }
}
```

**Comment by wellemut** [comment]
- [ ] Yes, open a tooltip above the centered pin to emphasis its a great idea
- [ ] Could you also make all un-seclected pins 50% transparent (as in the old version:  https://v0.kartevonmorgen.org/#/?entry=4203317cf55941048e27cf6c34b0d1d5&center=52.832,13.820&zoom=18.00&dropdowns=kvm) 
![grafik](https://user-images.githubusercontent.com/15019030/167503968-c48dc6fd-efff-40c0-8baf-5248c083b71d.png)


Yes this sound great
- [ ]  "default_zoom":6.0, - if you just come to the map
- [ ] "close_zoom":15.0, - if you click on an entry in the search result list or you hust have an entry by URL like  https://www.kartevonmorgen.org/m/main/e/cc33e558cf4749bf9c2f52a4731c1e10
- [ ] "reginional_zoom":12.0 - if you search for a region

**Comment by navid-kalaei** [comment]
- map sets its center to the entry if client is coming from a direct link and zooms to the close zoom
- the value of default zoom is now 6.0
- the value of close_zoom is now 15.5
- the value of regional_zoom is now 12.0

**Comment by wellemut** [comment]
Its great
- from https://www.kartevonmorgen.org/m/kvm/e/5ae2910155f64e7292a48f14f1328d91
- it flies to https://new.kartevonmorgen.org/m/main/e/5ae2910155f64e7292a48f14f1328d91?c=50.4500%2C30.5241&z=15.00
