### ISSUE TITLE
Install Favicon

### ISSUE THREAD

**Issue by navid-kalaei** [kartevonmorgen/kartevonmorgen.ts#129]
Favicon is not visible

**Comment by navid-kalaei** [comment]
That's a server bad behavior. It does not serve the `favicon.ico`. On the dev domain and localhost it renders the icon perfectly. @alex0107 could you please confirm server serves the file correctly? the facicon link is https://www.kartevonmorgen.org/favicon.ico . you can also check that from your devtoosl and filter with `favicon` . My guess is the icon does not exist in the public directory or you need to restart the container otherwise.

link to the dev domain: `https://dev.kartevonmorgen.org/favicon.ico`
the resource on the repo: https://github.com/kartevonmorgen/kartevonmorgen.ts/blob/develop/public/favicon.ico

**Comment by alex0107** [comment]
There was a wrong path in the config, I changed :)

**Comment by alex0107** [comment]
the path is? /public/favicon.ico

**Comment by navid-kalaei** [comment]
yes, and it seems to be fixed. thank you.

**Comment by wellemut** [comment]
Sooo beautiful

![grafik](https://user-images.githubusercontent.com/15019030/202799851-300714f6-006d-4ce9-ab69-9ab1a276e014.png)
