### ISSUE TITLE
Pointing ssr-Domain to the main URL  kartevonmorgen.org

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#133]
## Problem
some clients are using `ssr.kartevonmorgen.org` as their embedded map. and the ssr domain is hosted on Navid's server. this causes major problems:
1. an extra effort is needed to keep the ssr project up and running in production as the Navid's server is just configured for the development purposes.
2.  there's a fragile possibility of inconsistency that ssr's version get behind or ahead of the main domain.

## Solution
on the main server which hosts the main project, we reverse proxy the `ssr` domain to the main project. in that way we always will have a production ready project with two domains pointing to it. it can be done by nginx or any common web server like apache

**Comment by alex0107** [comment]
Should work now
