### ISSUE TITLE
Two rating kategories, but only one flower is growing

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#134]
I gave ratings in the first two categories, but only the yellow flower (which I rated first) is coloured
![grafik](https://user-images.githubusercontent.com/15019030/170860761-6a9c7a91-5b44-4a78-9996-fca825fc96a1.png)

https://www.kartevonmorgen.org/m/main/e/a98f49824b914a9187e83f27652cbef8?c=53.0363%2C12.7057&z=8.00&search=a22e

- [ ] could it be, that there is something broken?

**Comment by navid-kalaei** [comment]
the reason is it has a rate of 1 and -1, so the average is zero! you can verify but examining its rates from [the api](https://api.ofdb.io/v0/ratings/076e2adf25154689847586e01b14a818,debbddb9370341fa8a24c1b37e752b8d,624db022addb45a79f5ee53c8525291d,2520636d190642d093e23fe71da859c2).
