### ISSUE TITLE
Syncthing has stopped

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#135]
Synthing is not syncing anything anymore...
https://syncthing.kartevonmorgen.org/#

An Authorization seems to be missing: 
![grafik](https://user-images.githubusercontent.com/15019030/170873561-d3e471c5-a74b-4ca2-9684-176996f64041.png)

Most important is the "projects" folder

![grafik](https://user-images.githubusercontent.com/15019030/170873598-44ca073c-2c65-443b-b1a5-6cd7d5c01936.png)

**Comment by alex0107** [comment]
I will have a look at it :)

**Comment by alex0107** [comment]
Fixed
