### ISSUE TITLE
iframe steals the focus

### ISSUE THREAD

**Issue by navid-kalaei** [kartevonmorgen/kartevonmorgen.ts#137]
## Problem
when karte is embedded as iframes in other websites, it steals the focus resulting in jumping to the iframe and skipping its above content.

Why is a page, where the map is empedded directly scrolling to the map? https://blog.vonmorgen.org/
Thats annoying, because the users misses everything which is written above the map.

## How to find which element has focus
in the dev console execute `document.activeElement`

## Possible solutions
1. add tabindex=-1 to the ifram [refrence](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)
1. make the visible after the page is loaded. [reference](https://stackoverflow.com/a/7148477/3744479)
1. add script to page to jump to the top by changing focus to another element [reference](https://stackoverflow.com/questions/36775412/prevent-page-to-jumping-to-iframe)

**Comment by wellemut** [comment]
@navid-kalaei 
Thanks for your help.
But the problem still remains. tabindex=-1 does not help.

It is definitly related to the code of the map client, because before we never had the problem.

**Comment by navid-kalaei** [comment]
Ok , now we've got sure the tabindex is not working, i'll get dive down to the project code for more investigation.

**Comment by navid-kalaei** [comment]
I used Ant drawer for the sidebar. And it has the auto focus on by default. I've turned that off and tried to find the active element after the map is loaded and there was not any but the `body`. the problem should be solved now. please test in an iframe and let me know the result. @wellemut

**Comment by wellemut** [comment]
Great it is solved!
and not only on dev, but on producative too, which is embeded here: https://blog.vonmorgen.org/
How did you do that? Is there an auto-update to productive, that all of you changes go directly to productive @alex0107 ?

**Comment by navid-kalaei** [comment]
great to hear it's solved!

i have no control over the production server. so it should have been @alex0107 who updated the production.
