### ISSUE TITLE
entryform: Give warning if mail or website contains spacings

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#138]
## Problem
One of the most common errors is, that user write additional word/explanation in the field of email or website

## Solution
Show the field text in red, as long as it contains spaces or strange sings...

----
This is needed independently how far the backend can trim wrong content:
Related to: https://github.com/kartevonmorgen/openfairdb/issues/393

**Comment by navid-kalaei** [comment]
for the email validation I use the [isemail](https://www.npmjs.com/package/isemail) package. and before passing the values I trim the strings which means removing spaces from the beginning and the end of the email then checking for the validations. should i keep the extra spaces before passing the string to the validation function? or for better understanding could you please comment more test cases that what templates should pass and which ones should fail?

here is the reference for [isemail](https://www.npmjs.com/package/isemail)
[email validation of entries](https://github.com/kartevonmorgen/kartevonmorgen.ts/blob/362f6487142993c25c493f969718298d48adc8b1/components/EntryForm.tsx#L477)
[email validation of events](https://github.com/kartevonmorgen/kartevonmorgen.ts/blob/362f6487142993c25c493f969718298d48adc8b1/components/EventForm.tsx#L386)

**Comment by wellemut** [comment]
I think you should take whatever the users entered and pass it to the validation.

Because if somebody writes

`Private user@server.org Wien 
`
And you test in isemail
`Privateuser@server.orgWien 
`
Than you don't get an error although it's stupid.

Ich think better just visually indicate a problem.
If possible you can also add explainations under the field. I e.: No spaces allowed

**Comment by wellemut** [comment]
Frontend trims spacing form mail and website automatically
