### ISSUE TITLE
Make Germany default map-view

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#141]
## Problem
When you are on the landingpage and you click on "Map" button it leads you to https://www.kartevonmorgen.org/en/m/main and there you get automatically redirected to https://www.kartevonmorgen.org/en/m/main?c=50.8260%2C10.9200&z=15.00 
This is a very detailed view on fields close to Arnstadt which nobody really wants to see...

## Solution
change zoom to z=5.00
Make the redirection to https://www.kartevonmorgen.org/en/m/main?c=50.8280%2C10.9238&z=5.00

**Comment by wellemut** [comment]
@navid-kalaei i guess this strange detailed zooming in is just a config problem
In the config you say z=7 (which is too focused) projects/main/config.json
But the map seems not to be able to read this z factor...

**Comment by wellemut** [comment]
@navid-kalaei could you please care for this issue?

And this one here is similar https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/149

**Comment by navid-kalaei** [comment]
done on commit 4ddc165797d6e63baa22f0db026e62765bd37baf

**Comment by wellemut** [comment]
Perfectly running on https://dev.kartevonmorgen.org
-> produktive!
