### ISSUE TITLE
Report Entry button does not put the link-URL in the mail-body

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#143]
## Problem
This button should help to report specific entries.
![grafik](https://user-images.githubusercontent.com/15019030/182181758-0f678752-137c-49a9-9ca5-03b0af28bce5.png)

But the mails dont contain the entryURL
![grafik](https://user-images.githubusercontent.com/15019030/182181890-6f10f7d8-33c7-4cf8-8131-7eeb86827cc6.png)

## Solution
Please make sure the correct URL is provided.

**Comment by navid-kalaei** [comment]
done on commit 081fa3257f0ae604546d146eb7471cc8be643ed7

**Comment by wellemut** [comment]
Perfectly running on https://dev.kartevonmorgen.org/
![grafik](https://user-images.githubusercontent.com/15019030/210475005-6270bbb9-421a-49f4-a0c8-547231fe4ae2.png)

-> produktive!
