### ISSUE TITLE
location search on landing page is broken 

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#149]
Whatever you search for on the Landingpage, you get all correct suggestions but whatever you choose, the map you get is always the same (central Germany)

**Comment by navid-kalaei** [comment]
i could not reproduce that. even on the production server it's working flawlessly for me. shall we review it in a call? @wellemut

**Comment by wellemut** [comment]
You are right. Somehow it is working (again)
