### ISSUE TITLE
Add Impressum and Version-Number in the footer

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#157]
Please add
- [x] Imprint https://blog.vonmorgen.org/impressum/
- [x] Privacy https://blog.vonmorgen.org/datenschutzerklarung/
- [ ] and [new] Frontend Version-Number in the footer of the landingpage

Like on the old frontend https://v0.kartevonmorgen.org/#
![grafik](https://user-images.githubusercontent.com/15019030/223665950-c319afdd-9267-4875-84fe-345583d03792.png)

**Comment by navid-kalaei** [comment]
done. also realize the footer is not translated. I also did the translation. @wellemut

**Comment by wellemut** [comment]
Versionnumer was visible, but crushed
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/cf1a0f5d-98ef-404e-aba1-adae39c32508)

New landingpage is wordpress. So Map-Version should be visible on the map: https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/185
