### ISSUE TITLE
Landingpage: Update Team

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#162]
Update the Teamoverview:
![grafik](https://user-images.githubusercontent.com/15019030/106400730-9535e380-6420-11eb-940f-e06b92f34fdc.png)

Add new members:
Take all infos from: https://blog.vonmorgen.org/kontakt/
- Anna Rogun
- Laura Leichtle
- Uwe Klotz
- Manuel Molt
- Alex Reiner
- Heiko Hoffmann

**Comment by alex0107** [comment]
Original Logo:
![Logo Reiner IT-Systems GmbH](https://user-images.githubusercontent.com/17063865/231432210-dc250e82-ae5f-4771-be8d-e31afd948836.png)

**Comment by wellemut** [comment]
Perfect!  All Profile pictures are clickable
![grafik](https://user-images.githubusercontent.com/15019030/232957057-515ad518-def1-4539-9fa1-24ec5b22ad75.png)

**Comment by wellemut** [comment]
@alex0107 
- Why is this working on https://dev.kartevonmorgen.org/
![grafik](https://user-images.githubusercontent.com/15019030/234246817-2da39766-2d05-4100-b11d-45291515e1d2.png)
  - (This is working: https://dev.kartevonmorgen.org/_next/image?url=%2Fassets%2Fimg%2Fcreators%2Fideen.png&w=384&q=75)

- But broken on https://www.kartevonmorgen.org/
![grafik](https://user-images.githubusercontent.com/15019030/234246889-24384a8e-e607-4326-96b5-8e80e97dab3c.png)
  - https://www.kartevonmorgen.org/_next/image?url=%2Fassets%2Fimg%2Fcreators%2Fideen.png&w=384&q=75

(All other immages are running on https://www.kartevonmorgen.org/)

**Comment by wellemut** [comment]
Issue is solved.
Problem was related to the DevOp and the use of Syncthing. Now, we have an "asset" folder https://cloud.wechange.de/index.php/f/9751079, where alle immages need to be added to go live...
