### ISSUE TITLE
[BUG] Time on map is wrong for imported events

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#164]
**Describe the bug**
All Events on the new frontent are shown two hours ahead of time.
- An event that starts at 9:15 https://v0.kartevonmorgen.org/#/?entry=7456c64ac6ad425094a70ba5f6fdd9a5&zoom=15.00&dropdowns=kvm ![grafik](https://user-images.githubusercontent.com/15019030/232794708-ad1b4749-3c90-4175-9dd8-167423019339.png)

- is shown like 11:15 on the new frontend: https://www.kartevonmorgen.org/m/main/ev/7456c64ac6ad425094a70ba5f6fdd9a5?c=48.1342%2C7.8623&z=15.00&type=event ![grafik](https://user-images.githubusercontent.com/15019030/232794873-9c8d85cd-0066-4158-b026-5e5c52b8d137.png)

If you add an event on https://www.kartevonmorgen.org the problem is less visible because the frontend shows the time, as you have entered it. 
But if you import event vial ICal or you see events from old frontend, you see this error!

**To Reproduce**
1. Add an Event on the old frontend https://v0.kartevonmorgen.org (or import it via Ical Wordpress Plugin)
2. Compare what you see on v0. versus kartevonmorgen.org
3. If you have imported the event from another source, you clearly see the difference...

**Expected behavior**
No matter where I add an event to the map, it should be shown in the correct timezone (currently its summer time in Europe)

**Comment by navid-kalaei** [comment]
@wellemut the old front end does not show the time in the client's local time. it shows the in the GMK time zone. you can validate via https://www.unixtimestamp.com/. however the new front end displays the time in the clients time zone.

**Comment by wellemut** [comment]
@navid-kalaei is still dont trust your moment.js, although you think that their Timezone translation works fine.

Because we can export all events in caldav format. Here you finde all events from Emmendingen: http://openfairdb.org/api/v0/export/events.ical?bbox=48.02116128565783,7.498855590820313,48.249826274326274,8.171768188476564

And when I open this Ical feed in my calendar, it shows the correct times, like the imported feed:
![grafik](https://user-images.githubusercontent.com/15019030/235435171-d11dce04-97a4-4142-bf31-3b969d7ffce8.png)

So the time in list view: 
![grafik](https://user-images.githubusercontent.com/15019030/235435240-ac7e0a8b-3e15-41a4-bbfa-0b245ff0304c.png)
and map:
![grafik](https://user-images.githubusercontent.com/15019030/235435333-7fa22b8c-53cc-45df-967f-a495b2c01386.png)
 is wrong.

Also the imported Event in Wordpress is shown in the correct timezone: https://klimafitemmendingen.de/veranstaltungen/
![grafik](https://user-images.githubusercontent.com/15019030/235436199-094f342c-00b9-4a78-b9d6-9d1ba8b4718b.png)

**Comment by navid-kalaei** [comment]
the exporter and word press do not respect the timezone. they simply assume all times are UTC.

To validate that I should see a different time because I live in Iran and have a different time zone, right? But the time shown to me is the same as yours.

You can also pick a time from exported times and test that with https://www.unixtimestamp.com/ . Just see what time it will show for your local time.

![Screenshot from 2023-05-01 13-20-22](https://user-images.githubusercontent.com/7106251/235437613-d628edf8-2453-4375-81f8-50a89f8d86c1.png)

**Comment by wellemut** [comment]
@sjoerdtakken could it be, that the iCal export from WP to ofDB of your plugin does not respect the timezone of the event?

**Comment by wellemut** [comment]
@navid-kalaei you are right. Also the csv export http://openfairdb.org/api/v0/export/events.csv?bbox=48,7.5,48.25,8.17&end_min=1682978400 
has the UNIX Timestamp of 7pm 
![grafik](https://user-images.githubusercontent.com/15019030/235447394-4ba67985-810d-48e4-aafd-f33a7c0a574a.png)
and when i use https://www.unixtimestamp.com/ to transfer it, it shows 9pm (which is technically correctly converted from backend to frontend but wrong for the enduser)
![grafik](https://user-images.githubusercontent.com/15019030/235447565-720dfb44-2a01-4957-8afe-44cf8a435ce8.png)

Its also technically correct for events, which I enter manually by the new frontend: 
https://www.kartevonmorgen.org/m/main/ev/58a5f604661a433cae6a46a171e2315c?c=48.1974%2C7.6668&z=13.00&type=event
![grafik](https://user-images.githubusercontent.com/15019030/235448135-ae6b6608-efc1-4e67-8b54-10e5f2c9819c.png)
![grafik](https://user-images.githubusercontent.com/15019030/235448226-3fe64dcd-2a27-450a-8ab6-ee0c93070ed5.png)

the entry csv shows the timestamp of 7:15 UTC
![grafik](https://user-images.githubusercontent.com/15019030/235448260-5c192553-63a0-4ae1-884e-58906e00bc08.png)
which is 9:15 in MESZ
![grafik](https://user-images.githubusercontent.com/15019030/235448400-657e9172-828e-43c1-b6ee-65eb4ef68d65.png)


So it is definitly a Bug happening while import! @sjoerdtakken 

Also th

**Comment by sjoerdtakken** [comment]
I see it happens with all the events in the KVM. From the Wordpress Plugin I always the local Time (timezone is then Europe/Berlin) to the KVM. I now see I should transfer the UTC time to the OFDB. 
Okay I will change that, that makes sense. First I do I simple Fix and later I have to think about configuration possiblilities for different Timezones.

**Comment by wellemut** [comment]
**Sjoerd Takken, [Fr, 05.05.23 17:23]
Ich habe jetzt ein Quick und Dirty Fix gemacht, die Funktioniert jetzt und steht für Download bereit. https://github.com/kartevonmorgen/wp-kvm-syndication-toolbox/archive/refs/heads/main.zip

Sjoerd Takken, [Fr, 05.05.23 17:31]
Man muss dann aber bei Wordpress dafür sorgen das alle Events einmal geändert worden, damit die nach der KVM hochgeladen werden.

Sjoerd Takken, [Fr, 05.05.23 17:31]
ich habe der Status einfach einmal auf Entwurf und dann wieder auf Veröffenlichten gemacht.**

**Comment by sjoerdtakken** [comment]
There where still some problems with Feed import and timezones. I Fixed them Today:

[wp-kvm-syndication-toolbox.zip](https://github.com/kartevonmorgen/kartevonmorgen.ts/files/11429734/wp-kvm-syndication-toolbox.zip)
[wp-kvm-syndication-toolbox-log.txt](https://github.com/kartevonmorgen/kartevonmorgen.ts/files/11429736/wp-kvm-syndication-toolbox-log.txt)
