### ISSUE TITLE
[BUG] Linebreaks on an entry

### ISSUE THREAD

**Issue by alex0107** [kartevonmorgen/kartevonmorgen.ts#175]
## Problem
Linebreaks doesn't work yet in the new frontend if you open an entry

**To Reproduce**
1. Go to https://www.kartevonmorgen.org/m/main/e/a3f7793fd645449d9a844e350e377e61?c=52.4646%2C13.4087&z=15.00
2. Look at the description Frontend: <img width="387" alt="image" src="https://user-images.githubusercontent.com/17063865/234652851-018242e3-d844-4fad-af63-33c8482d7797.png">
4. Go to https://api.ofdb.io/v0/entries/a3f7793fd645449d9a844e350e377e61
5. Look at the description <img width="988" alt="image" src="https://user-images.githubusercontent.com/17063865/234652983-f6256ab2-8d3d-42bd-9fb8-aa81f0504b8b.png">
6. Linebreaks are missing

## Solution
- [x] Display linebreaks
On the old frontend, Navid developed linebreaks alredy: https://v0.kartevonmorgen.org/#/?entry=a3f7793fd645449d9a844e350e377e61&zoom=15.00&dropdowns=kvm ![grafik](https://user-images.githubusercontent.com/15019030/234744216-c8025bb9-859d-4df3-9437-0ca1e73d75ff.png)
See first issue: https://github.com/kartevonmorgen/kartevonmorgen/issues/663 and linked pull request

### Further Issue: 
-  Markdown in the entry description #788 https://github.com/kartevonmorgen/kartevonmorgen/issues/788

**Comment by wellemut** [comment]
Vielen Dank @alex0107 für den hinweis. In der Tat gab es Umbrüche bereits im alten Frontend: https://v0.kartevonmorgen.org/#/?entry=a3f7793fd645449d9a844e350e377e61&zoom=15.00&dropdowns=kvm

I will talk about it with @navid-kalaei next sprint planning...

**Comment by wellemut** [comment]
Linebreaks are working again!!! amazing
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/49303111-468b-4993-acb7-aedc24db81c9)
https://www.kartevonmorgen.org/m/main/e/82c4e99d99c843d8861c47977fa9c521?c=50.8260%2C10.9200&z=6.00
