### ISSUE TITLE
Correct Order of Adress

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#176]
## Problem
For Germans, its a weired format which we have currently
![grafik](https://user-images.githubusercontent.com/15019030/236350859-45555f76-3493-464f-81ee-7c15bc0352f5.png)
https://www.kartevonmorgen.org/m/main/e/02e3e0d0f89940bc9112bf3ecb0f33bc?c=46.9356%2C7.5520&z=16.00&search=radiesli+

## Solution
- [ ] Use the Adress-Sceme "Street Nr, ZIP City" street Nr, zip city, [state, country]
![grafik](https://user-images.githubusercontent.com/15019030/236350915-c2255a1e-cc86-428a-b90c-eb075fa0522f.png)
https://v0.kartevonmorgen.org/#/?entry=02e3e0d0f89940bc9112bf3ecb0f33bc&center=48.126,11.605&zoom=15.00&dropdowns=kvm

**Comment by navid-kalaei** [comment]
@wellemut I use [address-formatter](https://www.npmjs.com/package/@fragaria/address-formatter
) with country code 'DE'. it's the standard library for formatting addresses. please check again. if it still does not satisfies you then I will have to write a manual script, which would not be a good practice.

refrence: https://github.com/kartevonmorgen/kartevonmorgen.ts/blob/605713f69574d4f31b30589a35d23582354581a6/components/EntityAddress.tsx#L28

**Comment by wellemut** [comment]
Not working yet on https://dev.kartevonmorgen.org/m/main/e/02e3e0d0f89940bc9112bf3ecb0f33bc?c=46.9356%2C7.5520&z=16.00&search=radiesli

Order of Adress is still the same
and dev frontend keeps reloading all the time.

**Comment by navid-kalaei** [comment]
I fixed that. the problem was the street is named road, and zip is named postcode in the formatter.
@wellemut just an idea, do you like to make the formatter dependant on the locale or just set it to always DE. for example I can set the US format for the en locale

**Comment by wellemut** [comment]
That is great now!
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/92c004bb-9cdf-48a6-8864-b72b2b08f27a)
https://dev.kartevonmorgen.org/m/main/e/02e3e0d0f89940bc9112bf3ecb0f33bc?c=46.9356%2C7.5520&z=16.00&search=radiesli+

- [ ] Just the "," after Street Nr. is missing.

This way solves 95 of all usecases, I guess.
If it is easy to make it dependent of locale do it, Otherwiese its a feature request in the future...

**Comment by wellemut** [comment]
Th out of shelf library does not support "," in between Street and Zip, so we ignore it.

**Comment by wellemut** [comment]
perfectly deployed
