### ISSUE TITLE
entry detail page header should position currectly

### ISSUE THREAD

**Issue by navid-kalaei** [kartevonmorgen/kartevonmorgen.ts#183]
-  [ ]  go back button with white background
- [ ] Don't overlap back button with headline if no image.

**Comment by wellemut** [comment]
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/9749e856-0298-4a50-8ee2-c17b615f228f)
https://www.kartevonmorgen.org/m/main/e/6409bbe37e754df0afbd515d3cef5be3?center=51.166%2C6.350&zoom=6.00&search=Gw%C3%B6-regionalgruppe+energiefeld+gw%C3%B6+gemeinwohl%C3%B6konomie&dropdowns=ecg&c=49.7596%2C6.6442&z=16.00

![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/9c95cf73-bb4f-4ea0-84b8-415bc8e50c85)

https://www.kartevonmorgen.org/m/main/e/a2f0124a1220436dba8ddb6be9b08a6c?center=51.166%2C6.350&zoom=6.00&dropdowns=ecg&c=49.3027%2C8.9154&z=9.00
