### ISSUE TITLE
Footer for events should stick to the bottom

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#184]
https://dev.kartevonmorgen.org/m/main/ev/586fb52610434aa88726873e7dc609f8?c=50.6843%2C4.3726&z=7.00&type=event

**Comment by wellemut** [comment]
check if its fixed
![Uploading grafik.png…]()

**Comment by wellemut** [comment]
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/824a4bf5-6ed4-43e7-81e9-e15c92ca303c)

**Comment by wellemut** [comment]
Already a lot of time invested, but no solution found.

**Comment by navid-kalaei** [comment]
fixed on commit aa1327a85cc0f96dca2f2ad9c6380cb7eb5e6838
![kvm event footer](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/7106251/d402853e-5e45-4568-8f9d-883ffc1235c4)

**Comment by wellemut** [comment]
Oh yes, it's true. Footer is at the bottom now
https://dev.kartevonmorgen.org/m/main/ev/1b65d3e3d5484a5287089f20dc10d6e2?c=48.1066%2C7.8549&z=15.00&mapColorMode=gray

How did you manage to solve it?

**Comment by wellemut** [comment]
![grafik](https://github.com/user-attachments/assets/6c7036f5-050a-416f-8d72-b268d427bd67)
https://www.kartevonmorgen.org/m/main/ev/87e84c295b2440a8968c09f39a6c7150?c=50.8129%2C5.6030&z=6.00&mapColorMode=gray&type=event
