### ISSUE TITLE
[Feature] Version-Number in Burger-Menu or Map-Footer

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#185]
**User Story:** As an Admin I want to *see the Version-Number directly in the map app* in order to *be able to report problems, also in iframes, based on a specific version*.

## Problem:
- Nobody knows, which is the currently running Version.
- Version number is visible on the dev Landingpage: https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/157 but we are thinking of moving away from the landingpage

## Solution(s)

~- [ ] A. Integrate the Version number below the languge selection of the burger menu ~

- [ ] B. Integrate the version Number in the footer right corner next to the copyright of the map 
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/f84be124-5f9d-40e0-b018-d43868de6cf7)

![Image](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/d7391e67-95b0-430d-939a-bfa0c93fcbc4)

### Definition of Done
The moment a Product Backlog item meets the Definition of Done, an Increment is born. 

- [ ] ...
- [ ] Feature is implemented, without that other features are broken or undone
- [ ] Changerequests are linked to the issue and Reviewer are informed via chat

**Comment by wellemut** [comment]
Alex tries, if he can include the version number somewhere...

**Comment by alex0107** [comment]
@wellemut @navid-kalaei is it possible to add the current version number behind the left top-sidebar "Karte von morgen V1.2.0" (screenshot)? 
What do you mean?

<img width="392" alt="Bildschirmfoto 2024-01-04 um 22 16 15" src="https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/17063865/7c25684d-7d02-4694-9e2e-f94e3f188d9e">

**Comment by wellemut** [comment]
I think that's a spot where you would expect content.

Better burger menu
Or right button corner

**Comment by navid-kalaei** [comment]
The version is shown in the burger menu

**Comment by wellemut** [comment]
Purely amazing @navid-kalaei !
This will help us and @alex0107 in big fixing 

![Screenshot_20240710-213105~2.png](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/67bd8e7e-9098-42a5-9739-d73872a25910)
