### ISSUE TITLE
Search suggestions dont apear

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#188]
Could it be, that the search-proposal generator is not started yet?  @navid-kalaei ?
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/dc43600b-ec0e-45ae-882e-30ebff7a0d47)

**Comment by navid-kalaei** [comment]
this API is returning an empty response. that indicates the db for tag synchronizer is empty. @alex0107 please check the python script is running properly.  

API: https://www.kartevonmorgen.org/api/v0/entries/most-popular-tags
Guidance: https://github.com/kartevonmorgen/kartevonmorgen.ts/wiki/How-to-deploy:-tags-synchronizer

**Comment by wellemut** [comment]
- [ ] - Are there Tags starting with T, S or Z? (I think only the begining of the alphabet is working)
- [ ]  Do update the list of suggested tags more frequently: every hour! @alex0107 
- [ ] - Dont scan only the top 10 tags, @navid-kalaei scan the whole alphabet!
- [ ] - Scan all tags which are used 3 times or more @navid-kalaei 
- [ ] - Test if the new hashtag "Beak" is findable: https://www.kartevonmorgen.org/m/main?c=48.2475%2C7.3581&z=9.00&search=beka

**Comment by wellemut** [comment]
@navid-kalaei die alte python-Version vom tags-Syncronizer läuft nicht auf Alex Server.

Willst du das Script updaten?
Alex suggest, that you use the BACKEN-API "most-popular-tags" directly. With a delay of 500 ms the backend request the api directly

**Comment by alex0107** [comment]
Maybe close this issue? The Tagsync is running via crontab.
