### ISSUE TITLE
[BUG] Hashtags at the End of the alphabet are not proposed

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#192]
**Describe the bug**
When searching or adding a new entry, only hashtags from the first part of the alphabet are shown. 

**To Reproduce**
1. Go to https://www.kartevonmorgen.org/en/m/main?c=51.7610%2C9.5801&z=6.00
2. Start searching for "zusammenarbeit" "zivilgesellschaft" (dont copy the word, start typing!)
3. You won't get suggested these hashtags, although they are widely used (See https://www.kartevonmorgen.org/en/m/main?c=51.7610%2C9.5801&z=6.00&tag=zusammenarbeit and https://www.kartevonmorgen.org/en/m/main?c=51.7610%2C9.5801&z=6.00&tag=Zivilgesellschaft)

**Expected behavior**
1. When typing in the sarchbox or tag-field (also while mapping) all tags which are used more than 1 times, should be shown!

**Screenshots**
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/56c071cb-3597-4155-8b6e-6ccd867a8fca)

**Comment by alex0107** [comment]
<img width="400" alt="image" src="https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/17063865/1f6d95b9-7d32-45c5-8754-51565d9bf974">

Fixed with the hourly python-tagsync I think
