### ISSUE TITLE
Map Headline only visible, if name is given in config

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#200]

**Comment by wellemut** [comment]
We came back to the previeous close-sidebar-button without title.
But is the title possible if given in config?

**Comment by navid-kalaei** [comment]
implemented on commit b1f3523f6089eec7a4b8376782e028ec2909c9bd

to remove the title just set the sidebar title to an empty string in the config. An empty string is represented by double quotes. ""

**Comment by wellemut** [comment]
I will test it on the main system after deployment as I have no idea how to edit config files on dev

**Comment by wellemut** [comment]
perfectly working
Normal "main" map does not show headline.
But "openecolab" does https://www.kartevonmorgen.org/m/openecolab?mapColorMode=color&z=9.00&c=48.9432%2C8.9648
![grafik](https://github.com/user-attachments/assets/7fe06935-91c1-4b32-948a-2d945ac45592)
