### ISSUE TITLE
Avoid white screen after adding new entry on orgtag-view

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#211]
## Problem
You end up on a white screen without any Warning or Button, after you have added a new entry on an orgTag-View. (Because the orgTags stops the new entry to be loaded, as there is no approved version availiable)
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/159af3a2-7735-44fb-ad69-b23cbc370130)
https://www.kartevonmorgen.org/m/hessenwillsmessen/e/496f510a373c4f728134a69cfb1e7eac?c=50.5220%2C9.5423&z=13.00&tag=hessenwillsmessen&orgTag=hessenwillsmessen&mapColorMode=

**To Reproduce**
1. Go to https://www.kartevonmorgen.org/m/hessenwillsmessen?c=50.5184%2C9.5452&z=13.00&tag=hessenwillsmessen&orgTag=hessenwillsmessen (Important that URL contains `orgTag=hessenwillsmessen`)
2. Click on "**Add new Entry**"
3. Fill out all nessesary fields and click "Save"
4. Error: You end up on a white sidebar and it feels like it has gone wrong.

The Backend sends an empty Json file for the newly created entry:
https://api.ofdb.io/v0/entries/496f510a373c4f728134a69cfb1e7eac?org_tag=hessenwillsmessen

## Expected behavior**

- [ ] Whatever I open, whatever is loaded or not loaded, the **Back-Button** (1) should allways be visible on the entry detail page!!!
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/3afaf4de-3cb5-466d-bf7b-7f2aaebefed8)

### Two Options

- [ ] A. I see a message "Thank you for submitting a new entry. It's waiting for approval"

![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/79388df2-a42c-4f22-878d-5f6dc6358f83)
  - Advantage: The user knows, that his entry need approval and that he might not find it agai
  - Disadvantage: The user cant see his result and can not improve it instantly

- [ ] B. Always when clicking "Save" the orgTag is removed from the API which get send to the backend. 

https://api.ofdb.io/v0/entries/496f510a373c4f728134a69cfb1e7eac ~~?org_tag=hessenwillsmessen~~
Than the View for the creator is always the same like on maps without orgTag-View. 
But dont forget to add the `?org_tag=hessenwillsmessen` as soon as you leave the entry detail view
  - Advantage: The user can see the result, his new entry and his changes and can add further improvements directly.
  - Disadvantage: When he leaves his new entry, he will never find it again or not his changes and he does not no why...

**Comment by wellemut** [comment]
@navid-kalaei Do you prefer Option A or B for the solution of this bug?

**Comment by navid-kalaei** [comment]
I show a message that the entry does not exist or requires approval
![kvm-org tag](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/7106251/061e5f04-54b7-48f4-a167-9c7822bf825f)

**Comment by navid-kalaei** [comment]
fixed on commit a3fde95812a2ce079a3e62c97c534a9481396c69

**Comment by wellemut** [comment]
It's working amazingly great!
https://dev.kartevonmorgen.org/m/hessenwillsmessen/e/7950653a151c4a9f863de4d7b8c21999?c=50.7922%2C8.9115&z=14.00&tag=hessenwillsmessen&orgTag=hessenwillsmessen&mapColorMode=gray
![Screenshot_20240701-231834.png](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/763ce088-0eab-4965-a47f-a516cf04aaf7)

@navid-kalaei 
- [ ] can I find the new strings in the language file to translate it? 
- [ ] why is it not possible to edit existing entries. I get such a blocking error notification at the top:
![Screenshot_20240701-231741.png](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/9022ad32-f763-41da-aaff-904115013def)

Is it something which you changed? Or an old backend feature?

**Comment by wellemut** [comment]
@navid-kalaei could you please fix the button, so that it really brings you back to the search results. Currently nothing happens.

**Comment by navid-kalaei** [comment]
1. I added the click event on the back to the search result button on commit 2de858c22da56025d0b7e5e4e6a7d0cfd6e5dba3
2. the translation is here: https://github.com/kartevonmorgen/kartevonmorgen.ts/blob/d6b70b0eee29d3a5a1fdf6f5fdf4efdd9f5a2402/locales/en/map.json#L377
3. I believe the error comes from the back end because I don't have such a string `The tag is owned by an organization` on my side

**Comment by wellemut** [comment]
This is amazingly nice working now!
Just tested on this link: https://www.kartevonmorgen.org/m/hessenwillsmessen?c=50.5497%2C9.6720&z=17&mapColorMode=gray&tag=hessenwillsmessen&orgTag=hessenwillsmessen
