### ISSUE TITLE
Repair project config folders

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#215]
there are some projects that not only does not have the config file, but also they don't have other neccessary files like the checkbox
**the projects with only a broken config can be handled but the projects with a broken structure we cannot catch them**

- [x]   "BUND",
- [x]   "EM",
- [ ]   "Economy",
- [ ]   "FFF",
- [ ]   "Reuse",
- [ ]   "SDG",
- [ ]   "VAUDE",
- [ ]   "Wandeloasen",
- [ ]   "beka",
- [ ]   "colombia",
- [ ]   "comap",
- [ ]   "commons",
- [ ]   "culture",
- [ ]   "donut",
- [ ]   "ecg",
- [ ]   "edu",
- [ ]   "eurostat",
- [ ]   "ewnnrw",
- [ ]   "u00f6rderung",
- [ ]   "gemeinschaftsprojekte",
- [ ]   "hessenwillsmessen",
- [ ]   "klimafitkarte",
- [ ]   "kvm",
- [ ]   "lippe",
- [ ]   "Kopie",
- [ ]   "Vorlage",
- [ ]   "metamoderne",
- [ ]   "openecolab",
- [ ]   "refill",
- [ ]   "rennnw",
- [ ]   "future",
- [ ]   "solidarischestadtkarte",
- [ ]   "stopfossil",
- [ ]   "test",
- [ ]   "trier",
- [ ]   "bremen",
- [ ]   "vm",
- [ ]   "waldgarten",
- [ ]   "wandelregionen",
- [ ]   "wkl"

**Comment by wellemut** [comment]
I just had a little crash by opening https://www.kartevonmorgen.org/m/SDG?c=50.2121%2C9.2065&z=6.00&mapColorMode=gray&search=sdg11+stadtentwicklung, but nothing which i could reproduce
And status still online
![Uploading grafik.png…]()

**Comment by wellemut** [comment]
In some cases it keeps loadeing a long time, and markers are not shown like here: https://www.kartevonmorgen.org/m/vm?c=50.5867%2C12.8979&z=7.00&mapColorMode=gray&limit=300&search=fair+fairfashion+Kleidung+secondhand+futurefashion
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/f566f0a7-6d51-46dc-8fbc-eb9656030917)

**Comment by navid-kalaei** [comment]
I double checked the procedure. when a csv file like the dropdowns or the categories does not exist, we do not show that entity and the errors are handled. therefore for example if you don't need categories, simply remove the csv file.
however, the pins are compulsory for rendering balloons because they are images and I cannot have a fallback. so the projects that do not render the balloons, they do not have the directory public/projects/{project}/pins or their content is not correct.

**Comment by wellemut** [comment]
> the pins are compulsory for rendering balloons

I can not confirm that! i.e. "rennwk" has only a dropdown folder with csv file, but no Icon or pin-folder: https://www.kartevonmorgen.org/m/rennwk?c=50.5518%2C7.8223&z=7.00
But still, pins and baloons get shown:
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/e4630c19-5337-47c8-9518-79f3607e893e)

It seems to have a fallback which leads back to the main config?

**Comment by wellemut** [comment]
In this example, i just added a valid config, but no pins folder: https://www.kartevonmorgen.org/m/Reuse?c=49.1889%2C10.8325&z=6.00
Maybe that will crash...

**Comment by wellemut** [comment]
all projects running again, thanks to the latest release: https://github.com/kartevonmorgen/kartevonmorgen.ts/releases/tag/v1.2.7
