### ISSUE TITLE
[Feature] Add quantity

### ISSUE THREAD

**Issue by timmwille** [kartevonmorgen/kartevonmorgen.ts#217]
**User Story:** As a User I want *to see the quantity of search results* in order to *identify the scope of my targets*.

## Problem:
- Sometimes one searches for a type of location (e.g. #permaculture) 
- to identify the amount of results it would help to have a counter (total)
- to see the overlapping amount per location (sections, changes with zoom, optional)

## Solution(s)

- [ ] A. a quantity counter in view (vs total on Map?)
- [ ] B. a way to identify the amount per region with a lot of overlapping locations (optional)

**Describe alternatives you've considered**
some sort of csv export or build tool via API might work too, but all not optimal to easy get an idea about the knowledge/know how/topics spread across a region or compare. 

### Definition of Done
The moment a Product Backlog item meets the Definition of Done, an Increment is born. 

- [ ] A clear visible counter is in place or a simpler csv export of the view section
- [ ] Feature is implemented, without that other features are broken or undone

**Comment by wellemut** [comment]
Thank you timm for this clear description!

We have that feature request already here
https://github.com/kartevonmorgen/kartevonmorgen/issues/459

I will prioritise that one , as it also links to our FairSync project.
