### ISSUE TITLE
[BUG] ) sign beside Regpis entries 

### ISSUE THREAD

**Issue by timmwille** [kartevonmorgen/kartevonmorgen.ts#221]
## Problem
Every Pin with a specially designed color by csv has an ( sign left-below the actual pin
![grafik](https://github.com/user-attachments/assets/7cf1ec05-9af2-40f5-8e88-af59a4f04655)

(It does not happend to normal colored Pins (teal or green) and not to points, even if they have individual colors)

#### To Reproduce
1. Go to [a yellow marker location](https://www.kartevonmorgen.org/m/ideenhochdrei?c=50.0466%2C10.4480&z=7.00&search=Ideenhochdrei-partner+ideenhochdrei+kartevonmorgen) or to https://www.kartevonmorgen.org/m/openecolab?mapColorMode=color&tag=openecolab&orgTag=openecolab&c=51.1995%2C7.6148&z=6.00 (green pins)
3. Look at map below individual colord pins.
4. See a funny hovering `)` in the middle of the map

## Expected behavior
a clear map without artifacts

### Screenshots
tbd @martinschott
![grafik](https://github.com/user-attachments/assets/e651b8b8-3e90-46f0-a441-4e01011921c1)

**Desktop (please complete the following information):**
- any browser and device

**Comment by MartinSchott** [comment]
for example here: 

![grafik](https://github.com/user-attachments/assets/3a8b0323-0deb-4b94-a90f-9ce55cbc3051)

https://www.kartevonmorgen.org/m/openecolab/e/280f51d2c6eb4e5cb4299ee3a44b70ff?mapColorMode=color&tag=openecolab&orgTag=openecolab&z=12.00&c=48.8124%2C9.1865

**Comment by wellemut** [comment]
Please add title and better description.

I can't reproduce

**Comment by timmwille** [comment]
solved with the latest release v1.2.8 :tada: 

https://github.com/kartevonmorgen/kartevonmorgen.ts/releases/tag/v1.2.8

thx

**Comment by wellemut** [comment]
Thank you @navid-kalaei
