### ISSUE TITLE
Iframe Generator Button got lost

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#226]
## Problem
The Button "iframe" got lost in the sharing menu
![grafik](https://github.com/user-attachments/assets/a06e366a-a805-44d8-855c-814049997163)

instead there is the subscribe-button, which endpoint is not working yet.
- https://github.com/kartevonmorgen/openfairdb/issues/258
- https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/151

#### To Reproduce
1. Go to the map https://www.kartevonmorgen.org/m/kvm?c=50.8198%2C5.6030&z=6.00
2. Click on "share" down right
3. you cant find "share iframe code"

## Expected behavior
In dependently, if the "subscribe" button is activ or not, the "Embedd as ifrmes" button should never disappear
![Image](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/beaff8d3-2592-47f2-8c22-a0340c52203e)

**Additional context**
I guess, the problem came with the last release, when some dependencies were "rolled back" https://github.com/kartevonmorgen/kartevonmorgen.ts/compare/v1.2.7...v1.2.8

### Definiton of Done
- [ ] Sharing is possible just via a button
- [ ] a short explenation with screenshots is availiable under https://github.com/kartevonmorgen/kartevonmorgen.ts/wiki/Iframes

**Comment by wellemut** [comment]
@navid-kalaei please checkout, what could be the reason and estimate a story point number, how easy we could fix it?...

**Comment by navid-kalaei** [comment]
@wellemut it was my error during the development. I have made the subscription almost ready and before pushing to the production level I accidentally disable the sharing button disable instead. I made it back on commit 798439ba608c6de9fffdfb1e3cbeee16da62d9ae

**Comment by wellemut** [comment]
Thank you for fixing it @navid-kalaei 
It happens...

![Screenshot_20240923-214933~2.png](https://github.com/user-attachments/assets/d5f1dfc2-1bef-4640-8d11-ab1782e1df74)
Button is back again...
