### ISSUE TITLE
Burgermenu does not open

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#26]
When I try to open the burger menu on the map (https://vanya.kartevonmorgen.org/maps/main?lat=50.8260&lng=10.9200&zoom=7.00&type=2cd00bebec0c48ba9db761da48678134&type=77b3c33a92554bcf8e8c2c86cedd6f6f&type=c2dc278a2d6a4b9b8a50cb606fc017ed&start_min=1628200800&start_max=1628892000&isSidebarOpen=true) 

there is just nothing happening
![grafik](https://user-images.githubusercontent.com/15019030/128605306-4a7484a3-0609-4bcf-ba01-3889768c1059.png)

**Comment by navid-kalaei** [comment]
just for the sake of documentation
![Screenshot from 2022-01-06 21-11-31](https://user-images.githubusercontent.com/7106251/148426859-78dfccf3-de2d-41d2-9732-980488873c04.png)
