### ISSUE TITLE
How to name new Frontends?

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#3]
How to make it logical the way this repository is structured?

Slowtec and me prefer to give each frontend Version the Year, when we activated that fronend in this case https://github.com/kartevonmorgen/kartevonmorgen21

**Comment by flosse** [comment]
I'd recommend to name this repo `kartevonmorgen-ssr`

**Comment by wellemut** [comment]
We renamed it to https://github.com/kartevonmorgen/kartevonmorgen.ts
