### ISSUE TITLE
Landingpage: Open Map when clicking on the background of the city search

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#33]
# Problem
Many Cities are not found in the city search. Pleople get frustraited.
Some users do not want to search in a city but globally
For them the city search as entry for the map is a huge barrier.
The Menu link "Map" is not prominent enough to be found easily.

# Solution
1. [ ] Please open the map if somebody clicks on the baground of the city search. Wherever people click, the map is going to open.
2. [ ] Make the Button  "Show map..." if no city was found much bigger
3. [ ] Improve the city search https://github.com/kartevonmorgen/kartevonmorgen/issues/203

**Comment by navid-kalaei** [comment]
I transfered this issue from kartevonmorgen/kartevonmorgen to kartevonmorgen/kartevonmorgen-v1 because there was a need to link between the issues and the pull requests.
