### ISSUE TITLE
Location of "Add new entry button" below sharing button

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#35]
![grafik](https://user-images.githubusercontent.com/15019030/130359953-73a357c2-5d4d-4a69-8428-8360afccda0f.png)

![grafik](https://user-images.githubusercontent.com/15019030/130359959-ab50edd1-4f7b-4f73-8829-9569bedfb7a9.png)

**Comment by navid-kalaei** [comment]
and move it add new entry below sharing button

**Comment by wellemut** [comment]
At the moment we have the button twice.

We will remove one of them probably, after we did some usertestings!

![grafik](https://user-images.githubusercontent.com/15019030/140651165-bc9888cc-9bf3-48b9-84ed-09957857126e.png)
