### ISSUE TITLE
Add option for list-view to Iftrame creator

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#37]
## Current State
The sharing-popup only offers the iframe-code for the default map view. (which should always stay the default)

## New State
- [x] Above the Iframe code should be toogle-buttons (radio-buttons) to change the basis-URL of the iframe to change the view. 
![grafik](https://user-images.githubusercontent.com/15019030/132366762-b3d2637b-e0ec-45ed-b4f1-1dcbeea1c8ac.png)

### Options to choose
- [x] Map view https://ssr.kartevonmorgen.org/m/kvm 
- [x] List view https://ssr.kartevonmorgen.org/t/kvm 

#### Further options for later
If user has chosen Map-view there will be more options
- [ ] View only https://kartevonmorgen.org/mapAndEntryList.html#/ (without filter or add-button)
- [ ] Without Categories: https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/5

Only if an entry is selected: 
- [ ] Map only for single entries: https://kartevonmorgen.org/map.html#/?entry=4c20979fe0754e74875afa4308d73ce7&zoom=9.00
- [ ] Businesscard only for single entries https://kartevonmorgen.org/businesscard.html#/?entry=4c20979fe0754e74875afa4308d73ce7

If user has chosen List-view, there will be more options
- [ ] Show short description in new colum
- [ ] Show short description Below title
- [ ] Show Location in new cloum
- [ ] Show Location below time
- [ ] Make table sortable and searchable

## Add Name to Iframe-Code
- [x] Please add: <iframe id="kvm" name="kvm" ... to the code, so that the Iframe can be controlled from outside

**Comment by wellemut** [comment]
## User Requirements Freiburg
- [ ] einbetten: Der Code muss mit allergrößter Einfachheit zugänglich sein, einschl. Kopier-Button. Größtmögliche Ergonomie wäre für den Erfolg wichtig. 
- [ ] Für die Einbettung der Karte seid ihr ja schon gute Schritte zu einer Lösung gegangen, jetzt braucht es das noch für die Termin-Tabelle. Ja, das muss nicht von Anfang an da sein und dafür gehe ich auch gerne ins Fundraising. 
- [ ] wie wärs, die Funktion "Kalender einbetten" auch über das Hauptmenü und die Termin-Eingabemaske zugänglich zu machen? 
- [ ] Und wäre es denkbar, daß im Footer ein Button steht "Embed-Code kopieren"? Dann könnten Leute den ganz einfach übernehmen. Nur so als zusätzliche Erleichterung der Verbreitung.

**Comment by navid-kalaei** [comment]
> ## User Requirements Freiburg
> * [ ]  einbetten: Der Code muss mit allergrößter Einfachheit zugänglich sein, einschl. Kopier-Button. Größtmögliche Ergonomie wäre für den Erfolg wichtig.
> * [ ]  Für die Einbettung der Karte seid ihr ja schon gute Schritte zu einer Lösung gegangen, jetzt braucht es das noch für die Termin-Tabelle. Ja, das muss nicht von Anfang an da sein und dafür gehe ich auch gerne ins Fundraising.
> * [ ]  wie wärs, die Funktion "Kalender einbetten" auch über das Hauptmenü und die Termin-Eingabemaske zugänglich zu machen?
> * [ ]  Und wäre es denkbar, daß im Footer ein Button steht "Embed-Code kopieren"? Dann könnten Leute den ganz einfach übernehmen. Nur so als zusätzliche Erleichterung der Verbreitung.

could you please translate to English?

**Comment by wellemut** [comment]
>could you please translate to English?
done

**Comment by wellemut** [comment]
That is great @navid-kalaei ! So fast. Amazing!
![grafik](https://user-images.githubusercontent.com/15019030/140663769-06b47d8d-9320-4e8f-a8ec-fb43485b6824.png)

I also like, that if you close the sharing window while having selceted "Table" and you open it again, it is till on "table".

There ist just a double scroll-bar
![grafik](https://user-images.githubusercontent.com/15019030/140663722-14a001ac-ea21-413b-8659-ed1d13fb5f42.png)


Could you please make the default hight to 620px (instaed of 580) than its just one schroll bar.
Here is an example: https://blog.vonmorgen.org/iframes/#iframe-listenansicht

**Comment by navid-kalaei** [comment]
- the height for the table view embed code now is 620 on commit 756b34c1e5596786eacc5402f209e6e484cc3b68
- storing the state of the modal is possible but comes with code complexities. if it's not a necessity, I highly recommend to leave it as it is

**Comment by wellemut** [comment]
@navid-kalaei everythin is great now!
the way the sharing model works, is perfect. (it was a compliment, not a wish!)

**Comment by wellemut** [comment]
@navid-kalaei 
Somehow, all the sharing buttons and popup is allways in english, even the interface is in German:
![grafik](https://user-images.githubusercontent.com/15019030/140887634-7cbf1123-620b-412b-90cc-43519fe292fb.png)

Here
![grafik](https://user-images.githubusercontent.com/15019030/140887656-0a36e155-c5af-4bd4-935d-603273a92979.png)


Shall I provide any translation? Or did you just not connect these strings?

**Comment by navid-kalaei** [comment]
the translations for `Add`, `Map View`, and `Table View` are needed. the rest is connected
