### ISSUE TITLE
Integrate the Wasm-Module to propose tags

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#38]
To get fast Tag-Suggestions, the WASM-Module is optimised and adjusted to the backen:
Here is how you integrate it in your frontend:

    <script type="module">
      import init, { Kern } from '/kern.js';
      if (init && Kern) {
        init().then(() => {
          window.ofdb = { kern: new Kern() };
        });
      }
    </script>
https://github.com/kartevonmorgen/kartevonmorgen/blob/434bbf8a18ed670458261d927ebd73f7271b9bee/src/index.html#L26-L33

and here is, how you use it:

```
  popularTags: (max: Number, input?: String) => {
    // @ts-ignore
    if (window.ofdb && window.ofdb.kern) {
       // @ts-ignore
       return window.ofdb.kern.popular_tags(max, input);
    } else {
      return new Promise((_resolve, reject) => {
        reject(new Error("ofdb kern module not loaded!"));
      });
    }
  }
};
https://github.com/kartevonmorgen/kartevonmorgen/blob/434bbf8a18ed670458261d927ebd73f7271b9bee/src/WebAPI.ts#L506-L517
```

Here is an running example (with tests and benchmarks): https://github.com/kartevonmorgen/kartevonmorgen/tree/434bbf8a18ed670458261d927ebd73f7271b9bee/kern

You can test it here: https://kartevonmorgen.org/popular-tags/

**Comment by navid-kalaei** [comment]
filtering the tags on the front end is the worst of solutions I can ever imagine. it consumes memory and CPU from the client and will slow down the end user, regardless of the language or technology we use for the implementation. are sure you want to have the tag search functionality on the front end side @wellemut ?

**Comment by wellemut** [comment]
yes. we have to test that at least, because @flosse  says, it should be faster than the backend-API.
It has a maximum of 25.000 tags, which the frontend has to store. I guess theses few KB are handable. 

could you please leave the ssr domain as it is and integrate the WASM-Modul on a new subdomain like dev... than we can test it both!

**Comment by navid-kalaei** [comment]
the tag suggestion is done on the front end server.
