### ISSUE TITLE
Geocoding: Wrong usage of the town-field

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#42]
## Problem
When adding a new entry and clicking on the map, it finds the coordinates and partly the adress.
But it does it wrong
![grafik](https://user-images.githubusercontent.com/15019030/136188729-b943dc30-7d79-4e73-9bad-8dd0e918c88d.png)

## Intended:
Instead of "town" there should be the name of the town (not the type)
And Additionally to the Street below, it should also grab the House-Number of that place
(The ZIP Field works correctly)

--- 
### Similar Issues:
- Geocoding: Find Coordinats if the adress is given #41

**Comment by navid-kalaei** [comment]
resolved on commit 91b6bdc3b4e3b63d4ca0a8bf18eef30d8a71a9ed
