### ISSUE TITLE
Maker Footer sticky at the buttom

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#45]
Make the footer stick at the buttom, even if the text above is small
![grafik](https://user-images.githubusercontent.com/15019030/136806761-b6606e6a-58db-4c7d-a88d-714a84702ef7.png)

example: 
https://ssr.kartevonmorgen.org/m/main/e/b99eed5461914243876106af0ddec8ea?c=49.4025%2C9.9783&z=10.00

if the entry is longer than one page, the footer can be at the very end.

**Comment by wellemut** [comment]
@ziedavid Navid could not find a solution for this, we hope that together with you we can solve it.

**Comment by navid-kalaei** [comment]
implemented on commit 89c05a9bb1e46f8fb3e733421dffce2ddda65889

also it's fully responsive. it means when the height of the window changes the footer will move to the correct position

**Comment by wellemut** [comment]
working perfectly on https://dev.kartevonmorgen.org/m/main/e/4911fc5acfec4362bbe7241e2c32a416?c=49.9394%2C11.5955&z=15.00
