### ISSUE TITLE
If no start_min is given, start with today ALSO IN LIST-VIEW

### ISSUE THREAD

**Issue by navid-kalaei** [kartevonmorgen/kartevonmorgen.ts#46]
In most of the cases if you have an event list, the first events should be the next upcomming. Thats why it makes sense, that if no timeframe is given, the list and map shows automatically max, 100 events, starting from today.
I.e. It is working on the map: https://ssr.kartevonmorgen.org/m/main?c=50.8260%2C10.9200&z=7.00&type=event

- [ ] Please make it work, also in the list-view https://ssr.kartevonmorgen.org/t/kvm 

But in some cases, people also want to show a certain selection of events, i.e. all that happend last year. In those cases you can use the URL attribute `&start_min=1628546400&start_max=1629237600` 
i.e. : 
- Map: https://ssr.kartevonmorgen.org/m/main?c=50.8260%2C10.9200&z=7.00&type=event&start_min=1628546400
- List: https://ssr.kartevonmorgen.org/t/kvm?start_min=1616198400

(We just need a UX, to control this)

**Comment by wellemut** [comment]
Here it is still not working.  https://dev.kartevonmorgen.org/t/main?text=&tag=&bbox=48.5%2C3.4%2C53.03%2C18.42
The Tables shows events from March 2019

But it should show events only staring today, as it has no start parameter

**Comment by navid-kalaei** [comment]
fixed on commit 05e1f952eff40e3c00128109ecfe31d4ce2287eb

**Comment by wellemut** [comment]
Thank you!
Amazingling nice how it is working now https://ssr.kartevonmorgen.org/t/main?text=&tag=&bbox=48.50204750525715%2C3.4167480468750004%2C53.034607110319044%2C18.424072265625004&start_min=1636412400&end_min=1636498799
