### ISSUE TITLE
Start directly the Initiative Formular (not the type chooser first) when creating a new entry

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#47]
- [x] Load the Initiave formular right at the beginning, withouth the typechooser first!!!
~~- [ ] have the type chooser opened already~~
- [x] when editing a company, do not automatically change type to Initiative while open edit-form
![grafik](https://user-images.githubusercontent.com/15019030/137754350-40eb74f4-6050-4f7e-9435-9445d36aec01.png)

- [x] integrate the correct translations
  - [x]  and show the extended explenation fields for initiatives...

![grafik](https://user-images.githubusercontent.com/15019030/137753246-5d997276-bd73-45cf-94f9-543ea272056d.png)

**Comment by navid-kalaei** [comment]
implemented on commit cf3e9d6acab65a80be27cdafc592ea161522ab5b

I found the opening of the select menu unnecessary. to what extend do we need that behavior?

**Comment by wellemut** [comment]
Perfectly working not on one page when creating a new entry

- [ ] When editing an entry, it should be possibel to change between initiative and company

**Comment by wellemut** [comment]
The increment of this issue got undone by completing this issue: https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/96
Therefore i have it repoended.

**Comment by wellemut** [comment]
Thats working perfectly.

But opening the event formular by direct link still is not possible

On the old Frontend we have https://v0.kartevonmorgen.org/#/?addentry=event&search=%23wasser where you endup directly in the formular
There is also that redirection from https://kartevonmorgen.org/#/?addentry=event&search=%23wasser to https://dev.kartevonmorgen.org/m/main/e/create?tag=wasser&addentry=event&c=50.8260%2C10.9200&z=6.00 which opens the entry form, but not for events. that also fails for `addentry=company`

Is that another Bug/Issue or does it relates to here?

**Comment by wellemut** [comment]
Created an issue for the last comment: https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/47#issuecomment-1514081438

**Comment by wellemut** [comment]
The Bug is suddenly back:
- [ ] when editing a company, do not automatically change type to Initiative while open edit-form

I opened a not for it: https://github.com/orgs/kartevonmorgen/projects/12#card-89104378

**Comment by wellemut** [comment]
Its working not https://dev.kartevonmorgen.org/m/main/e/b7abc16a1f5d427a8ffe9dabd513d91f?c=51.0094%2C10.0497&z=9.00
