### ISSUE TITLE
Remove character-limit of description and add counter instead

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#49]
The length of the description should not be limitted!
See the issue of the old frontend: https://github.com/kartevonmorgen/kartevonmorgen/issues/675#issuecomment-592445091

- [ ] Add a warning when exceeding 250 characters
- [ ] Add a characters count, so people know, how much they have written.

**Comment by navid-kalaei** [comment]
implemented on commits 40015b0256d83587b6ab1080409f502642d9daa9 and 96549a691f7fd7800af89e1473a041ea440aa608

**Comment by wellemut** [comment]
![grafik](https://user-images.githubusercontent.com/15019030/143270729-2563fe57-17cb-4321-b591-1017432b36f4.png)

Working nicely 
![grafik](https://user-images.githubusercontent.com/15019030/143270790-4b531029-4d6c-49b1-9d5c-f3b940249a00.png)
