### ISSUE TITLE
Unable to type in Tags-Filter Field

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#51]
- I can not type or paste anything in the field for filtering tags!
![grafik](https://user-images.githubusercontent.com/15019030/137953883-23279cb7-686b-48dc-9caa-17093aa8a62d.png)
- Choosing an entry

**Comment by navid-kalaei** [comment]
fixed on commit c163d84c24cd0ddc626df66609ac893aab13f7f5

**Comment by wellemut** [comment]
Amazing! Just fluently working. Thanks
