### ISSUE TITLE
Start to search after delay, but without having to hit the search button

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#52]
## Problem
- The Search feels buggy and unreliable, direct feedback is missing, and strange behaviours because filters dont get removed.

### Steps to reproduce

1. Got to https://ssr.kartevonmorgen.org/m/main?c=49.0955%2C-5.8887&z=3.00
2. Choose a suggestion in the searchline
3. :x:  Nothing is happing, even after waiting a few seconds
4. Press enter
5. :white_check_mark:  Filtering starts

### Intendet behaviour

- [ ] In step 3, the search should start automatically after a delay of 500ms without user input (like the search is starting already automatically after selecting a tag in the field below.
- [ ] We would not need the search-button
- [ ]  But if we leave the search button, the search should also start by pressing `Enter`

**Comment by navid-kalaei** [comment]
developed on commit 7987e98437c46bfe16903a2d03510025ed003820

- on selecting an option the search starts automatically
- on changing the input text the search starts automatically
- the text in the palceholder is translated
- the search button is eliminated

**Comment by wellemut** [comment]
waiting for test deploy

**Comment by wellemut** [comment]
Its working great now! https://dev.kartevonmorgen.org/
