### ISSUE TITLE
Mailadress is not saved!

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#53]
Mailadress ist not saved

### Steps to reproduce
1. add a new entry on https://ssr.kartevonmorgen.org
2. give in all inforamtion, including mailadress (Validation works)
3. After you saved, the mailadress is not shown. (Its also missing in the old frontend https://kartevonmorgen.org)

You can also just open an existing enty and save it again. The Mailadress is deleted afterwards!
Previously it was working. But at that time, the mailadress was mandatory: https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/43
like it is still in co-map.ru https://co-map.ru/maps/main/entries/1b48d927b8974df3a9d5ba215fd9d6ee

**Comment by navid-kalaei** [comment]
implemented on commit 979e7d87c0abd2b40ac06aa32bd2f5d4a5d7552f

**Comment by wellemut** [comment]
Perfect! Thanks a lot! its working!
