### ISSUE TITLE
Mobile-View: Hide Sidebar button is missing

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#57]
## Problem
On mobile view, there is no button to close the sidebar!
But on such small screen you need it the most
![grafik](https://user-images.githubusercontent.com/15019030/138029899-1ad41dfa-e79e-4f08-8e59-46d3eaddd604.png)

## Intended
- [ ] Show the close button similar to the desktop view
- [ ] But make the button wider or make the whole sidebar swipe-abel
- [ ] Make the sidebar cover 90% of the screen, if the screen is smaller than 400px https://github.com/kartevonmorgen/kartevonmorgen/issues/770
![grafik](https://user-images.githubusercontent.com/15019030/138030007-81555eaf-6401-4e9f-9608-3e488a62faf2.png)

**Comment by navid-kalaei** [comment]
implemented on commit 83cf69c2e2a6deeb64e597b194fae80ca15d4f80

**Comment by wellemut** [comment]
Its working perfectly!
Just that the sidebar is getting too narrow, but this is another issue: https://github.com/kartevonmorgen/kartevonmorgen/issues/770#issuecomment-960265983
![grafik](https://user-images.githubusercontent.com/15019030/140228482-b8bbab1c-4731-44f0-ab7b-4384e84a9f75.png)
