### ISSUE TITLE
Mouse over Pin: make the Title oriented to the right

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#58]
## Problem
Browsing the map is ether boring, because you only see pins, or annoying, because you would have to click on every one of them

## Solution
Prio 1
- [x] Show the title of the entry while hovering the pin (mouse over)
  - [x] If its an Event, show the Date too https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/65

Prio 2
  - [ ] Any Idea we could use on mobile phones insteas of hover? Should the first tip just open the tooltip and then you have to click on the tooltip to open the entry detail?

Prio 3
- [ ] Is it possible to highlight the corresponding pin on the map while hovering the search results in the left sidebar? https://github.com/kartevonmorgen/kartevonmorgen/issues/817

**Comment by navid-kalaei** [comment]
Prio 1 is on commit d2e9d4d4ed526120d764d763121f794dc855f4c4

**Comment by wellemut** [comment]
Its perfect on dev....
![grafik](https://user-images.githubusercontent.com/15019030/143266033-fa918118-a92e-49af-90fc-0814e4d624a6.png)

**Comment by wellemut** [comment]
@navid-kalaei

**Comment by navid-kalaei** [comment]
I set the direction to `always` right. in this case we cover most of the cases. at least we can get sure no tooltip gets hidden under the sidebar. and for the pins at the right edge most of the time the first word can be shown, which would be enough to find the entry from the sidebar or start a new search

**Comment by wellemut** [comment]
Thank you very much!
