### ISSUE TITLE
Show Badge on Filter-Button, when a filter is active

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#62]
## Problem
By default, the filter-menu is hidden and just the searchbar visible
- if a user is on the map, he does not see, if there is an active filter, stopping him from finding, what he is looking for.

## Solution
- [ ] Give the Filter-Button-Icon a red badge / dot, when at least on tag is activated.
![grafik](https://user-images.githubusercontent.com/15019030/140232129-f7e610b1-2522-442c-b5b6-e49142b43c0c.png)

- [ ] If there is no extra effort, you can also directly show the number of active filters /tags: https://ant.design/components/badge/
![grafik](https://user-images.githubusercontent.com/15019030/140231943-59cf0d69-3dd1-49bb-b619-cbd67cd5f1f7.png)

**Comment by navid-kalaei** [comment]
the badge will be shown if any of these parameters is set in the URL
- tag
- type
- end_min
- start_max

**Comment by wellemut** [comment]
I dont see any badge so far on https://new.kartevonmorgen.org/m/main?c=49.6996%2C4.6802&z=7.00&search=bio+Lebensmittel+vegan+weltladen&tag=fair

**Comment by wellemut** [comment]
It works really beautiful!

![grafik](https://user-images.githubusercontent.com/15019030/165250855-d491dea9-376a-4240-bc89-89c754ba2286.png)
