### ISSUE TITLE
Make Links on entry detail clickable

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#63]
- [x] Make Profile URL a link
- [x] Make the Profile-Mail a mailto: link
- [x] Make the Tags clickable (start a search)
- [x] Make the Adress a link to navigation-App and on desktop to https://graphhopper.com (see old feture to understand API)

**Comment by navid-kalaei** [comment]
done

**Comment by wellemut** [comment]
Just perfectly working here: https://dev.kartevonmorgen.org/m/main/e/16e7a8f88c2040588c3061a0a6c15194?c=49.9477%2C11.5749&z=15.00
