### ISSUE TITLE
Centralize on the Pin and zoom in when clicking on the corresponding search result

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#64]
## Current Behaviour
- I click on a search result in the left of https://dev.kartevonmorgen.org/m/main?c=50.8233%2C10.9204&z=7.00
  - Or open any random entry by URL like: https://dev.kartevonmorgen.org/m/main/e/d0f92347a02647e9a502e998fa92c4fe
- The Entry is opening but nothing is happending on the map
- Problem: I can not see, where this entry is located

## Intended behaviour
- I click on a search result (like here https://kartevonmorgen.org/#/?center=50.834,10.300&zoom=6.00&dropdowns=kvm)
- The Entry is opening and the the map centers to this entry and zooms in to z=15 (like here https://kartevonmorgen.org/#/?entry=34cde89dddc94e22b22398c98e970076&center=47.812,13.032&zoom=15.00&dropdowns=kvm)

**Comment by navid-kalaei** [comment]
developed on commit b5126ed3e3e2372a0effd6233c71cb8938fe2477

**Comment by wellemut** [comment]
This is working great: https://dev.kartevonmorgen.org/m/main/e/052e477fbf02412c83d4400db9cdefe2?c=52.4739%2C13.4043&z=15.00
