### ISSUE TITLE
Hovering pin: Show Date of Event next to the title

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#65]
## Problem
- Date and Time of an event are rather hidden. On the map you cant see the date at all.
- The Weekday is missing completly

## Solution
- Show the Date directly in the Map next to the title in the tooltip-lable: (Format: 21.10.) (An Example, how useres fix it know: https://kartevonmorgen.org/#/?entry=50f8d1a45d244f9cbd86cf86dfa2c76b&center=50.802,8.785&zoom=12.00&categories=event)
- Add the Weekday in the Searchresultlist and on the Entry-Profil (Format Mo. 26.10.)
- Add the start-time in the Searchresultlist (Format: 26.10. 20:00) or, if it is over more days add the ending day instead (Format: 26.10.-28.10.)
- Add the Weekday and year on the entry detail (Format Mo. 26.10.2021 17:00-20:00 or if more days Do. 30.9.2021 14:00 - Fr. 3.10.2021 16:00) 

![grafik](https://user-images.githubusercontent.com/15019030/97124929-5c57e580-1732-11eb-818e-394338cc9e98.png)

**Comment by navid-kalaei** [comment]
implemented on commit d2e9d4d4ed526120d764d763121f794dc855f4c4

**Comment by wellemut** [comment]
This issue is done
![grafik](https://user-images.githubusercontent.com/15019030/147926198-1161f048-0113-4312-a58d-741e057cbabf.png)
it works beautifully on https://dev.kartevonmorgen.org/m/main/ev/6fc157db6ea14339a85bf39449dbe11e?c=48.5570%2C8.4566&z=15.00
