### ISSUE TITLE
Checkbogs filter below searchfield based on csv file

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#68]
In some cases, checkboxes are just esier than dropdown
Therefore during the Hackathon, the co-map.ru got an extra filter-menü right below the searchbar
![grafik](https://user-images.githubusercontent.com/15019030/143424854-cc38d118-07bb-4f3c-b2f5-709eaea3f8ed.png)

So far it is hard-coded and needs to be connected to the csv file

---
you find further explenations of this functions in the wiki: https://github.com/kartevonmorgen/kartevonmorgen.ts/wiki/Dropdown-and-cutomized-categories

**Comment by navid-kalaei** [comment]
developed on commits 9751b6cdfa966104dd7432a6e8dac29bf2390b75 and a14201d08720111b7e460a2a5dfb07d06f0eb397 . the features are alive on the dev domain

**Comment by navid-kalaei** [comment]
@wellemut  shall we close this issue?

**Comment by wellemut** [comment]
I was no table to test it yet...

**Comment by navid-kalaei** [comment]
> I was no table to test it yet...

what can I provide for you to facilitate the testing procedure?

**Comment by wellemut** [comment]
I just depends that the new frontend with the Syncthing is working! https://new.kartevonmorgen.org/ So its rather a question to Alex...

**Comment by navid-kalaei** [comment]
@wellemut shall we close this issue?
