### ISSUE TITLE
Build-Process

### ISSUE THREAD

**Issue by alex0107** [kartevonmorgen/kartevonmorgen.ts#70]
After testing the Dockerfile, the build-process stucks at 

`(Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)`

after I run 
`yarn run build:dev`

@navid-kalaei:
I have updated Next.js from version 10 to 12 and as the consequence Babel is replaced with SWC. SWC has a strange behavior both on the local machine and the server that when you are building the project as you said it stocks at the end. hence it should some how get terminated, either with CTRL+C or killing the process

Is there any solution?

**Comment by navid-kalaei** [comment]
please also see https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/2#issuecomment-983831113 at #2
