### ISSUE TITLE
Default zoom and center to Germany

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#76]
Most of our users come from Germany.

## Problem
But when I go to dev.karte... the map opens at c=0.0000%2C0.0000&z=0.00 which is very stupid.

## Solution
could you set these default start values to c=50.6808%2C-17.9297&z=3.00&sidebar=hidden

For our German version you should use this: c=50.9584%2C9.0802&z=7.00 That works alreay perfectly on https://ssr.kartevonmorgen.org

**Comment by navid-kalaei** [comment]
the commit 7987e98437c46bfe16903a2d03510025ed003820 related to issue #52 has broken the route initialization.

**Comment by wellemut** [comment]
@alex0107 is the https://new.kartevonmorgen.org Domain self updating, or do I have to give you a call, when you should update it?
Or can @navid-kalaei update your server by himself?

**Comment by wellemut** [comment]
Perfekt!
