### ISSUE TITLE
Rating Button is missing, if no rating is given yet

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#77]
If no single rating is added to an entry yet, there is no rating button at all!

Example: 
https://kvm-frontend.test.rhw24.it/m/main/e/2c685720a8e946ae9cb6de119dec516a?c=38.5309%2C-0.5775&z=15.00
![grafik](https://user-images.githubusercontent.com/15019030/147941750-5af8828a-ddee-479b-a275-ae5dd6bf87e6.png)

This has already a rating, therefore it is visible: https://kvm-frontend.test.rhw24.it/m/main/e/b349dc487e284681847c9f517fd8a52e?c=40.3990%2C-3.6849&z=15.00

**Comment by navid-kalaei** [comment]
fixed on 6daae0f

**Comment by wellemut** [comment]
Perfectly working on https://dev.kartevonmorgen.org/m/main/e/6e36aa7a1a284d8083de9dbf696b99e2?c=38.7894%2C0.1633&z=15.00
