### ISSUE TITLE
Regions-Dropdown: Manual city input not working

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#78]
## Intendet Behaviour:
Its working here: https://kartevonmorgen.org/#/?center=48.137,11.575&zoom=13.00&dropdowns=rennnw
You should be able to add any citiy name in the regions filed, and the map jumps to the city.

## Problem
In the current version, it works only with the given cities from the dropdown list: https://dev.kartevonmorgen.org/m/main?c=47.9961%2C7.8494&z=15.00
But manually added cities do not work.

---
Similar issues: https://github.com/kartevonmorgen/kartevonmorgen/issues/776

**Comment by navid-kalaei** [comment]
now the region search also begins by pressing enter: c826ed6

**Comment by wellemut** [comment]
Great, not it is working on https://dev.kartevonmorgen.org
![grafik](https://user-images.githubusercontent.com/15019030/148618944-5e01d182-eb7b-4cd3-a671-3c7f0f53e8e1.png)

@navid-kalaei  

- [ ] could you please set the zoom-in factor to `z=12.00` (instead of `z=6`)

**Comment by wellemut** [comment]
Great, it works no on https://dev.kartevonmorgen.org/m/main?c=48.1269%2C7.8102&z=12.00

**Comment by navid-kalaei** [comment]
@wellemut why the issue is open again?
