### ISSUE TITLE
Contact Person not saved

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#79]
When editing an entry on https://new.kartevonmorgen.org/m/main/e/8c542b39cf9b4b72a9330132307f5e6f?c=48.1353%2C7.8315&z=15.00

the contact person is lost after editing.
- it shown correctly
- but not saved.

**Comment by navid-kalaei** [comment]
fixed on f13cb2e7d472d7044c7ae00e1cb146bf13252db7

**Comment by wellemut** [comment]
Very nice! its working fine on https://dev.kartevonmorgen.org/m/main/e/49bf9bacb10243409f1b06ea65367244?c=49.3982%2C8.8045&z=15.00&tag=b%C3%BCrgerkarte

**Comment by navid-kalaei** [comment]
@wellemut is there any reasons to keep this issue open?
