### ISSUE TITLE
remained features

### ISSUE THREAD

**Issue by navid-kalaei** [kartevonmorgen/kartevonmorgen.ts#8]
## Requirements

1. - [x] opening hours
2. - [x] custom links
3. - [x] the even filter
6. - [x] burger button

## Sprint week 26
5. - [x] add tag recommender in the the event and entry forms
1. - [x] Open sidebar when clicking on entry
1. - [x] Colour of the company
3. - [x] left-side color to differenciate entrytypes
3. - [x] Integrat the individual dropdowns
4. - [x] Introduce the hashtag-suggestions to the searchbar, but do not filter but just search.
3. - [x] integrat the time of the event, next line below title in this format like the list https://blog.vonmorgen.org/freiburg/
4. - [x] reduce the space beween the burger menu items
5. - [x] stick the burger menu button to the right
6. - [x] add the three line icon the the burger menu button

### Sprint week 27
15. - [x] add comment
1. - [x] translations
9. - [x] locate me on the map
14. - [x] padding of the detail views
16. - [x] fix locale transition from the landing to the map
17. - [x] make the search input wilder on the landing page
18. - [x] zoom out button if no entry is found
1. - [ ] Make the sidebar larger on the smartphone https://github.com/kartevonmorgen/kartevonmorgen/issues/358#issue-282379610
1. - [x] find all tags, not just the 500 most used ones https://github.com/kartevonmorgen/kartevonmorgen-v1/issues/9
1. - [x] In the rating there is missing the last category "Transparency"
1. - [x] close sidebar button not in the footer, but on the edge of the sidebare

### Sprint week 30 old iframes
32. - [x] Rating flower
1. - [x] Add Title and Rating to the ratings 
![grafik](https://user-images.githubusercontent.com/15019030/126649887-5cac91a6-6b76-4629-91d6-a8a0bdd45764.png)
34. - [x] share modal (for hacaton)
1. - [x] Mailadress and Phone number are **not mandatory!**
1. - [x] Dont validat phonnumbers at all! (Its just too complicate, and we do not call people by bot.
1. - [x] Do not show seconds while adding an event!
2. - [x] 9. New URL- https://github.com/kartevonmorgen/kartevonmorgen/issues/813#issuecomment-896947432
https://www.kartevonmorgen.org/search=hello&geo=50.830,10.920
vonmorgen.org/map/kvm
https://ssr.kartevonmorgen.org/maps/main?lat=50.205033264943346&lng=14.775154964717052&zoom=4&slug=main&type=2cd00bebec0c48ba9db761da48678134&type=77b3c33a92554bcf8e8c2c86cedd6f6f&type=c2dc278a2d6a4b9b8a50cb606fc017ed

### Sprint week 35
- [x] The citiy search on the landing page does not redirect to the map but shows an errow.
- [x] locate me in home page https://github.com/kartevonmorgen/kartevonmorgen-v1/issues/36
- [x] Header immag ration https://github.com/kartevonmorgen/kartevonmorgen-v1/issues/28 
- [ ] Keep Entry-Footer at the buttom, even if no ratings are given.
- [x] Do not send a start_max by default but `end_min` should be today at midnight 23:59 (Old request https://kartevonmorgen.org/api/v0/events?bbox=47.6946854875851,10.231618881225588,47.75732936839834,10.396413803100588&start_min=1630627200) `start_max` oder `end_max` are not needed, just optionals as soon as we have filters in the frontend.
26. - [x] Geolocation of the Pins has to start already after filled in the first field of the adress. Directly zoom into it and place the pin. (Exactly like in the old version -> copy code)

### not urgent
3. - [x] renn https://www.kartevonmorgen.org/renn.html#/ old iframe
4. https://www.kartevonmorgen.org/hlnug.html#/ new iframe
4. - [x] buissiness card
5. - [x] map only

# Not to do!
- Login-Service (its sufficient if user can login on https://openfairdb.org/)
- We will soon solve the subscriptoin process easily just by mail: https://github.com/kartevonmorgen/openfairdb/issues/258

   1. - [x] Time-range chooser: Take the time, even if user does not click "ok". (as in the old version)
      1. - [x] Hashtags should be shown, even if they are just usde one time. 

## Pad of Features
Some financial agreements are made here https://wechange.de/project/team-von-morgen/document/refactoring-frontend/edit/

**Comment by wellemut** [comment]
@navid-kalaei 
Forget about the login-System for now!
Subscriptions will be handled just by mail: https://github.com/kartevonmorgen/openfairdb/issues/258

**Comment by wellemut** [comment]
- [ ] In the rating there is missing the last category "Transparency"

**Comment by navid-kalaei** [comment]
## Changes Since Hackaton
1. add rating flower to the entry details
2. do not show broken space if no image is available on the entity details
3. show zoom out button in the sidebar if no search result is available
4. remove the text "contact" from the entity detail divider
5. remove the text "tags" from the entity detail divider
6. add more padding to the entity details and entity forms
7. add transparency radio button to the rating form
8. phone number is not mandatory in the entity form
9. do not validate phone number in the entity form
10. email is not mandatory in the entity form
11. do not validate email in the entity form
12. search input is wider on the homepage
13. add the 'copy' button with no bug. in the version provided at hackaton the query params where dropped
14. add the sharing modal to the map

## Features that needs to be clarified
1. parsing the time from the date-picker in the forms technically is not possible because the times only can get passed through functions by click on the OK button
2. tags will get shown even they get used once on the production. and the reason it's not working on the dev environment is the cron job is stopped on purpose
3. do not show the second on adding an event? more clarification is needed about this requirement

**Comment by wellemut** [comment]
https://github.com/kartevonmorgen/openfairdb/pull/346#discussion_r693512390

**Comment by wellemut** [comment]
Thank you very much!!! I love it!

To 1.: Validation: Do we need to validate the URL, or can you make it always clickable?
To 7: Sidebar collapse button: The behaviour is great. But the button could be much bigger, so that you can hit it on the mobile too...
For 10. and 18.: I love the new URL. Much more beautiful! But why does the old URL work with a normal , ?center=48.520,8.652 but the new one needs this c=50.7747%2C7.6575 ?

Really great!

**Comment by wellemut** [comment]
This is done

![grafik](https://user-images.githubusercontent.com/15019030/121786003-8b39a380-cbbd-11eb-9645-ec85e95b0e71.png)

**Comment by navid-kalaei** [comment]
translation for not a valid email

**Comment by wellemut** [comment]
- Ration of immages is perfect. But hight should not be more than in the old version. And Background of too narrow immages should be white not grey.

-

**Comment by wellemut** [comment]
- [ ] Set the pin and Lan/long when the map flew to the right place: https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/41
- [ ] Remove horizontal double scrollbar on entry detail https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/40
- [ ]

**Comment by navid-kalaei** [comment]
@wellemut shall we close this issue or there are features remained?

**Comment by wellemut** [comment]
Yes, lets close this power issue! Thanks a lot!
