### ISSUE TITLE
Time box filter menu below location-filter

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#82]
# Problem
The Backend allows some useful features, which we do not support in the frontend:
- limit the timeframe of events in which they are shown
- Limit the max. number of search result
- Set a general prefilter

# Solution
Create a filter menue
![Folie8](https://user-images.githubusercontent.com/15019030/75644350-5745a380-5c42-11ea-8016-b5d8a8ba8329.PNG)
![Folie9](https://user-images.githubusercontent.com/15019030/75644356-5a409400-5c42-11ea-9825-1a43ef05c56f.PNG)
![Folie10](https://user-images.githubusercontent.com/15019030/75644360-5dd41b00-5c42-11ea-9fb7-1b2b23660209.PNG)
![Folie11](https://user-images.githubusercontent.com/15019030/75644364-60cf0b80-5c42-11ea-880c-46a23a31cb04.PNG)
![Folie12](https://user-images.githubusercontent.com/15019030/75644368-64629280-5c42-11ea-94b2-0886c90db54d.PNG)
![Folie13](https://user-images.githubusercontent.com/15019030/75644370-688eb000-5c42-11ea-868a-2d1379b94e6b.PNG)
![Folie14](https://user-images.githubusercontent.com/15019030/75644372-6a587380-5c42-11ea-91f2-cc960b56b72a.PNG)

![Folie15](https://user-images.githubusercontent.com/15019030/75644346-53b21c80-5c42-11ea-90c0-672273fbeced.PNG)

**Comment by wellemut** [comment]
That looks great and the timepicker is working very well!

**just that the search results do not match really the timeframe i selected.**
- frontend sends `&start_min=XXX` but backend API is searching (automatically) by `&end_min=YYY` too, But YYY does not change, if I select an earlier date.
- > Example I: This Frontedn-URL: https://dev.kartevonmorgen.org/m/main?c=49.3251%2C8.4814&z=7.00&start_min=1609455600&type=event sends this backend-call: https://dev.ofdb.io/v0/events?bbox=46.93526088057719,0.9777832031250001,51.60437164681676,15.985107421875002&tag=&start_min=1609455600&end_min=1641596399
- > `Start_min=1.1.2020` < `end_min=1.1.2022` which means, I look for events that have started later than 1.1.2020 and are ending after 1.1.2022. That means I see only events ending in the future and not the past events, I wanted to see
- > Example II: If I manipulate the Frontend-URL and **add the `end_min`-attribute which I set to the intended time** (same as `start_min`) it works: https://dev.kartevonmorgen.org/m/main?c=49.3251%2C8.4814&z=7.00&start_min=1609455600&end_min=1609455600&type=event -> https://dev.kartevonmorgen.org/m/main?c=49.3251%2C8.4814&z=7.00&start_min=1609455600&end_min=1609455600&type=event (deleting the `start_min`-Attribut in the Frontend-URL does not work, because it gets automatically added by the default-value which is 'today')
- [ ] **Solution: let the frontend set directly the `end_min` value and forget about `start_min`**

- [ ] But something on the search-query broke. What ever I search for, it just does not start searching (but tags-filter are working)
- [ ] Search-Suggestions in the searchfield do not finish the current word (or replace, what I have started to type) but instead add a new word 
- Starting to type:
![grafik](https://user-images.githubusercontent.com/15019030/148615019-8adc3414-ba34-480d-860c-a82802a40267.png)
- Selecting an item just adds the word after my first letters
![grafik](https://user-images.githubusercontent.com/15019030/148615138-6bc962a7-d161-468e-9ea1-0e6e7e585a9f.png)

**Comment by navid-kalaei** [comment]
the search tokens are fixes on commit 2909d011290a65dad409be5f84e694e8d9a61ae7 . the time frame explanation was fluffy, let's discuss it online.

**Comment by navid-kalaei** [comment]
now, the first time picker is end_min and the later one is start_max. the default for the end_min is start of today. and no defaults are considered for start_max, start_min, and end_max. the changes are made both for the map and the table view

**Comment by wellemut** [comment]
Its working perfectly now!!!

Further improvement of the date-pciker when adding events here: https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/104
