### ISSUE TITLE
Order of Positive impact ratings

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#95]
## Problem
- Pin-Colours do not match
![grafik](https://user-images.githubusercontent.com/15019030/152726891-5db1e549-f28e-4ca2-ac04-95f5287d5dd6.png)

## Solution
- [ ] In the rating-Formular: Move "Renewability" to the 2nd Position
![grafik](https://user-images.githubusercontent.com/15019030/152727265-99d1587f-8eaa-4de0-b153-23f21a15551c.png)

- [ ] Make sure, the Order of the 6 Dimension and the colour is as followed:
![grafik](https://user-images.githubusercontent.com/15019030/152727005-71dc26b6-e3fb-4946-bf0b-c24b3231c681.png)
Compare to this entry: https://kartevonmorgen.org/#/?entry=a3f7793fd645449d9a844e350e377e61&center=52.465,13.409&zoom=15.00&dropdowns=kvm

In this entry, the Pin-colors match already, but not the category-headlines: https://new.kartevonmorgen.org/en/m/main/e/a3f7793fd645449d9a844e350e377e61?c=52.4646%2C13.4087&z=15.00&search=nahw%C3%A4rme
![grafik](https://user-images.githubusercontent.com/15019030/152727507-ac8b506e-0122-4938-8211-87beb1942766.png)

**Comment by wellemut** [comment]
The Order ist still wrong:
![grafik](https://user-images.githubusercontent.com/15019030/160301604-1c7896fd-2d6f-4335-a337-03570db6add6.png)

![grafik](https://user-images.githubusercontent.com/15019030/160301620-01bea30e-c852-4ef1-874c-78cc2f49911f.png)


- [ ] Erneuerbarkeit has to move above fairness in the entry-detail
- [ ] Erneuerbarkeit has to move above fairness in rating formular

**Comment by navid-kalaei** [comment]
@wellemut new changes are live on the dev domain

**Comment by wellemut** [comment]
Perfect! this is solved an live! https://www.kartevonmorgen.org/m/main/e/a3f7793fd645449d9a844e350e377e61?c=52.4647%2C13.4088&z=12.00
![grafik](https://user-images.githubusercontent.com/15019030/165101111-6dfb8ec2-5c1d-45cb-b568-c5ec19f0471f.png)
