### ISSUE TITLE
Do not delete Text in the entry-mask when changing type

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#96]
### Problem
- Go to https://www.kartevonmorgen.org/m/main/e/create
- Start typing title and description
- Change the type from initiative to company
-> Everything you have entered so fare gets deletet!

### Solution
- [x] It should be possible to change the entry type any time without deleting the text which was entered already. 

Exception: The timeframe can be lost, when the user changes from event to another type.

**Comment by alex0107** [comment]
![image](https://user-images.githubusercontent.com/17063865/152738084-cb12f62f-09a5-4b03-9300-09e0782534ac.png)

**Comment by wellemut** [comment]
@alex0107 hat das was mit diesem Issue zu tun?
Wo genau tritt das problem auf? was funktioniert nicht?

**Comment by alex0107** [comment]
Wenn ich auf Speichern klicke und Unternehmen ausgewählt habe, wird das in der Console beim speichern ausgegeben - aber ich glaub das hat nur indirekt mit dem Issue zu tun

**Comment by wellemut** [comment]
@alex0107 Das Problem ist glaub nur auf der Dev-Domain. Auf new.kartevonmorgen.org funktioniert bei mir alles.

**Comment by wellemut** [comment]
- [ ] Do not set typ automatically to "Initiative" when clicking edit
- [ ] Why checkbox-tags get removed by changing type?

**Comment by wellemut** [comment]
Solved
on https://dev.kartevonmorgen.org/m/main/e/create?c=50.8260%2C10.9200&z=6.00 i can change the type without loosing content from the formular 

![grafik](https://user-images.githubusercontent.com/15019030/232958863-b20ecad2-e3eb-4f17-b830-c351e129f58a.png)
