### ISSUE TITLE
load csv file for the regional and category filters

### ISSUE THREAD

**Issue by navid-kalaei** [kartevonmorgen/kartevonmorgen.ts#98]
## Problem
we expected dropdowns to be based on csv files. however, on opening a the map a project name other than `main` still the main categories and regions were shown.

## Cause of the Problem
in the original format of KVM dropdowns were defined in the url query param of `dropdowns`, and we followed the same principle on the new version too. however, as the consequence of evolution, we considered the project name as the single source of truth for configurations and runtime files. and I missed to apply the project name principle for the dropdowns too.

**Comment by wellemut** [comment]
Thank you navid. So I guess that was just a code-problem and the wiki page is still correct: https://github.com/kartevonmorgen/kartevonmorgen.ts/wiki/How-to-customize:-categories-dropdown

**Comment by navid-kalaei** [comment]
## Introduction
at Feb 18, I've got a report from @wellemut  and @alex0107 that the dropdowns and the checkboxes have bugs.

## Problems
1. the categories are not shown neighter in the tag search, nor the main searchbar.
1. checkboxes are shown on the main project even when the public directory is empty.

## Observations
1. the checkbox directory for project `main` is empty but the endpoint response has data
1. the endpoint for categories is functional but returns empty data

## Hypothesis
1. the directory listed from the OS is not the same as the relative directory of project
1. the "current working directory" of the project is somewhere else than the domain directory

## Tests
1. copied the archived csv files of [NextCloud](https://nextcloud.wechange.de/s/sdrzpRTgETtkNzC) (link is broken) onto the local machine. the categories for `rennnw`, `ecg`, `comap`, and `main` were all functional.
![comap](https://user-images.githubusercontent.com/7106251/154814631-8a329420-54ce-4b43-bbcc-0f70b8b2e42b.png)
![ecg](https://user-images.githubusercontent.com/7106251/154814632-4e67e13e-e38a-4f38-8164-09cc1f144de8.png)
![main](https://user-images.githubusercontent.com/7106251/154814633-8e00fad1-208b-445b-897d-edcd7ecae3e6.png)
![rennnw](https://user-images.githubusercontent.com/7106251/154814635-26e7b709-0130-4cf4-8a36-a5e6fe6999e1.png)

1. removed the checkboxes csv file from main and the checkboxes did not render in the filters
![main checkbox](https://user-images.githubusercontent.com/7106251/154814837-69dee135-8214-445b-9227-ee3a068681a7.png)


## Conclusion
the directory listed by os is not the same as the project directory. for example if the project is running in a docker container, the csv files should get copied in the public folder which is inside the container. in other words, for any reasons the project cannot see the csv files. and commonly it's because of wrong directories

**Comment by wellemut** [comment]
The Problem is solved: https://github.com/kartevonmorgen/kartevonmorgen/issues/804
The csv-lists get perfectly loaded.
